export const SET_ACCOMMODATION_TYPES = "SET_ACCOMMODATION_TYPES";
export const SET_CREATE_ACCOMMODATION_STEP = "SET_CREATE_ACCOMMODATION_STEP";
export const INCREMENT_CURRENT_STEP = "INCREMENT_CURRENT_STEP";
export const DECREMENT_CURRENT_STEP = "DECREMENT_CURRENT_STEP";
