export const SET_MY_LISTINGS_LOADING = "SET_MY_LISTINGS_LOADING";
export const SET_ACCOMMODATION_DRAFTS = "SET_ACCOMMODATION_DRAFTS";
export const SET_ACCOMMODATIONS = "SET_ACCOMMODATIONS";
export const SET_ACCOMMODATION = "SET_ACCOMMODATION";