export const SET_MY_LISTINGS_LOADING = "SET_MY_LISTINGS_LOADING";
export const SET_ACCOMMODATION_DRAFTS = "SET_ACCOMMODATION_DRAFTS";
export const SET_MY_LISTINGS = "SET_MY_LISTINGS";
export const SET_CURRENT_LISTING = "SET_CURRENT_LISTING";
