<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('currencies', function (Blueprint $table) {
            $table->id();
            $table->string('code', 3)->unique();
            $table->jsonb('name');
            $table->string('symbol', 10);
            $table->boolean('is_active')->default(true);
            $table->boolean('is_default')->default(false);
            $table->boolean('is_base')->default(false); // Is this the base currency (EUR)
            $table->integer('decimal_places')->default(2);
            $table->string('symbol_position', 10)->default('before'); // before, after
            $table->string('thousands_separator', 5)->default(',');
            $table->string('decimal_separator', 5)->default('.');
            $table->integer('sort_order')->default(0); // For display ordering
            $table->timestamps();

            $table->index(['code', 'is_active']);
            $table->index('is_default');
            $table->index('is_base');

            $table->index('code');
        });

        DB::table('currencies')->insert([
            // Major Global Currencies
            ['code' => 'USD', 'name' => json_encode(['en' => 'US Dollar']), 'symbol' => '$', 'is_active' => true, 'is_default' => true, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'EUR', 'name' => json_encode(['en' => 'Euro']), 'symbol' => '€', 'is_active' => true, 'is_default' => false, 'is_base' => true, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ','],
            ['code' => 'GBP', 'name' => json_encode(['en' => 'British Pound']), 'symbol' => '£', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'AUD', 'name' => json_encode(['en' => 'Australian Dollar']), 'symbol' => 'A$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'CAD', 'name' => json_encode(['en' => 'Canadian Dollar']), 'symbol' => 'C$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'JPY', 'name' => json_encode(['en' => 'Japanese Yen']), 'symbol' => '¥', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'CNY', 'name' => json_encode(['en' => 'Chinese Yuan']), 'symbol' => '¥', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],

            // North America
            ['code' => 'MXN', 'name' => json_encode(['en' => 'Mexican Peso']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'CUP', 'name' => json_encode(['en' => 'Cuban Peso']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'JMD', 'name' => json_encode(['en' => 'Jamaican Dollar']), 'symbol' => 'J$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'GTQ', 'name' => json_encode(['en' => 'Guatemalan Quetzal']), 'symbol' => 'Q', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'HNL', 'name' => json_encode(['en' => 'Honduran Lempira']), 'symbol' => 'L', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'CRC', 'name' => json_encode(['en' => 'Costa Rican Colón']), 'symbol' => '₡', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'NIO', 'name' => json_encode(['en' => 'Nicaraguan Córdoba']), 'symbol' => 'C$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'PAB', 'name' => json_encode(['en' => 'Panamanian Balboa']), 'symbol' => 'B/.', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
            ['code' => 'BZD', 'name' => json_encode(['en' => 'Belize Dollar']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],

            // South America
            ['code' => 'BRL', 'name' => json_encode(['en' => 'Brazilian Real']), 'symbol' => 'R$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'ARS', 'name' => json_encode(['en' => 'Argentine Peso']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'CLP', 'name' => json_encode(['en' => 'Chilean Peso']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'COP', 'name' => json_encode(['en' => 'Colombian Peso']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'PEN', 'name' => json_encode(['en' => 'Peruvian Sol']), 'symbol' => 'S/', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'VES', 'name' => json_encode(['en' => 'Venezuelan Bolívar']), 'symbol' => 'Bs.S', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'UYU', 'name' => json_encode(['en' => 'Uruguayan Peso']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'PYG', 'name' => json_encode(['en' => 'Paraguayan Guaraní']), 'symbol' => '₲', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'BOB', 'name' => json_encode(['en' => 'Bolivian Boliviano']), 'symbol' => 'Bs', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'ECU', 'name' => json_encode(['en' => 'Ecuadorian Sucre']), 'symbol' => 'S/.', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'GYD', 'name' => json_encode(['en' => 'Guyanese Dollar']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SRD', 'name' => json_encode(['en' => 'Surinamese Dollar']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],

            // Europe
            ['code' => 'NOK', 'name' => json_encode(['en' => 'Norwegian Krone']), 'symbol' => 'kr', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'SEK', 'name' => json_encode(['en' => 'Swedish Krona']), 'symbol' => 'kr', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'CHF', 'name' => json_encode(['en' => 'Swiss Franc']), 'symbol' => 'CHF', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => "'", 'decimal_separator' => '.' ],
            ['code' => 'PLN', 'name' => json_encode(['en' => 'Polish Złoty']), 'symbol' => 'zł', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'HUF', 'name' => json_encode(['en' => 'Hungarian Forint']), 'symbol' => 'Ft', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'CZK', 'name' => json_encode(['en' => 'Czech Koruna']), 'symbol' => 'Kč', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'HRK', 'name' => json_encode(['en' => 'Croatian Kuna']), 'symbol' => 'kn', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'RSD', 'name' => json_encode(['en' => 'Serbian Dinar']), 'symbol' => 'дин', 'is_active' => true, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'BAM', 'name' => json_encode(['en' => 'Bosnia and Herzegovina Convertible Mark']), 'symbol' => 'KM', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'MKD', 'name' => json_encode(['en' => 'Macedonian Denar']), 'symbol' => 'ден', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'ALL', 'name' => json_encode(['en' => 'Albanian Lek']), 'symbol' => 'L', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'TRY', 'name' => json_encode(['en' => 'Turkish Lira']), 'symbol' => '₺', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'UAH', 'name' => json_encode(['en' => 'Ukrainian Hryvnia']), 'symbol' => '₴', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'BYN', 'name' => json_encode(['en' => 'Belarusian Ruble']), 'symbol' => 'Br', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'MDL', 'name' => json_encode(['en' => 'Moldovan Leu']), 'symbol' => 'L', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'RUB', 'name' => json_encode(['en' => 'Russian Ruble']), 'symbol' => '₽', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'GEL', 'name' => json_encode(['en' => 'Georgian Lari']), 'symbol' => '₾', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'AMD', 'name' => json_encode(['en' => 'Armenian Dram']), 'symbol' => '֏', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],
            ['code' => 'AZN', 'name' => json_encode(['en' => 'Azerbaijani Manat']), 'symbol' => '₼', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ' ', 'decimal_separator' => ',' ],

            // Asia-Pacific
            ['code' => 'INR', 'name' => json_encode(['en' => 'Indian Rupee']), 'symbol' => '₹', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'KRW', 'name' => json_encode(['en' => 'South Korean Won']), 'symbol' => '₩', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SGD', 'name' => json_encode(['en' => 'Singapore Dollar']), 'symbol' => 'S$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'HKD', 'name' => json_encode(['en' => 'Hong Kong Dollar']), 'symbol' => 'HK$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'TWD', 'name' => json_encode(['en' => 'Taiwan Dollar']), 'symbol' => 'NT$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'MYR', 'name' => json_encode(['en' => 'Malaysian Ringgit']), 'symbol' => 'RM', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'THB', 'name' => json_encode(['en' => 'Thai Baht']), 'symbol' => '฿', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'IDR', 'name' => json_encode(['en' => 'Indonesian Rupiah']), 'symbol' => 'Rp', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'PHP', 'name' => json_encode(['en' => 'Philippine Peso']), 'symbol' => '₱', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'VND', 'name' => json_encode(['en' => 'Vietnamese Dong']), 'symbol' => '₫', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'LAK', 'name' => json_encode(['en' => 'Lao Kip']), 'symbol' => '₭', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'KHR', 'name' => json_encode(['en' => 'Cambodian Riel']), 'symbol' => '៛', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'MMK', 'name' => json_encode(['en' => 'Myanmar Kyat']), 'symbol' => 'K', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'BND', 'name' => json_encode(['en' => 'Brunei Dollar']), 'symbol' => 'B$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'LKR', 'name' => json_encode(['en' => 'Sri Lankan Rupee']), 'symbol' => '₨', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'NPR', 'name' => json_encode(['en' => 'Nepalese Rupee']), 'symbol' => '₨', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'BTN', 'name' => json_encode(['en' => 'Bhutanese Ngultrum']), 'symbol' => 'Nu.', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'MOP', 'name' => json_encode(['en' => 'Macanese Pataca']), 'symbol' => 'MOP$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'KPW', 'name' => json_encode(['en' => 'North Korean Won']), 'symbol' => '₩', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'MNT', 'name' => json_encode(['en' => 'Mongolian Tugrik']), 'symbol' => '₮', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'PKR', 'name' => json_encode(['en' => 'Pakistani Rupee']), 'symbol' => '₨', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'BDT', 'name' => json_encode(['en' => 'Bangladeshi Taka']), 'symbol' => '৳', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'AFN', 'name' => json_encode(['en' => 'Afghan Afghani']), 'symbol' => '؋', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'UZS', 'name' => json_encode(['en' => 'Uzbekistani Som']), 'symbol' => "so'm", 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'KZT', 'name' => json_encode(['en' => 'Kazakhstani Tenge']), 'symbol' => '₸', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'KGS', 'name' => json_encode(['en' => 'Kyrgyzstani Som']), 'symbol' => 'лв', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'TJS', 'name' => json_encode(['en' => 'Tajikistani Somoni']), 'symbol' => 'ЅМ', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'TMT', 'name' => json_encode(['en' => 'Turkmenistani Manat']), 'symbol' => 'T', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => ',', 'decimal_separator' => '.' ],

            // Middle East
            ['code' => 'SAR', 'name' => json_encode(['en' => 'Saudi Riyal']), 'symbol' => '﷼', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'AED', 'name' => json_encode(['en' => 'UAE Dirham']), 'symbol' => 'د.إ', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'QAR', 'name' => json_encode(['en' => 'Qatari Riyal']), 'symbol' => '﷼', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'KWD', 'name' => json_encode(['en' => 'Kuwaiti Dinar']), 'symbol' => 'د.ك', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 3, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'BHD', 'name' => json_encode(['en' => 'Bahraini Dinar']), 'symbol' => 'ب.د', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 3, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'OMR', 'name' => json_encode(['en' => 'Omani Rial']), 'symbol' => '﷼', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 3, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'ILS', 'name' => json_encode(['en' => 'Israeli New Shekel']), 'symbol' => '₪', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'JOD', 'name' => json_encode(['en' => 'Jordanian Dinar']), 'symbol' => 'د.ا', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 3, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'LBP', 'name' => json_encode(['en' => 'Lebanese Pound']), 'symbol' => '£', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SYP', 'name' => json_encode(['en' => 'Syrian Pound']), 'symbol' => '£', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'IRR', 'name' => json_encode(['en' => 'Iranian Rial']), 'symbol' => '﷼', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'IQD', 'name' => json_encode(['en' => 'Iraqi Dinar']), 'symbol' => 'ع.د', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 3, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'YER', 'name' => json_encode(['en' => 'Yemeni Rial']), 'symbol' => '﷼', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],

            // Africa
            ['code' => 'ZAR', 'name' => json_encode(['en' => 'South African Rand']), 'symbol' => 'R', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ' ', 'decimal_separator' => '.' ],
            ['code' => 'NGN', 'name' => json_encode(['en' => 'Nigerian Naira']), 'symbol' => '₦', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'EGP', 'name' => json_encode(['en' => 'Egyptian Pound']), 'symbol' => '£', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'KES', 'name' => json_encode(['en' => 'Kenyan Shilling']), 'symbol' => 'KSh', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'TZS', 'name' => json_encode(['en' => 'Tanzanian Shilling']), 'symbol' => 'TSh', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'UGX', 'name' => json_encode(['en' => 'Ugandan Shilling']), 'symbol' => 'USh', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'GMD', 'name' => json_encode(['en' => 'Gambian Dalasi']), 'symbol' => 'D', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SHP', 'name' => json_encode(['en' => 'Saint Helena Pound']), 'symbol' => '£', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SLL', 'name' => json_encode(['en' => 'Sierra Leonean Leone']), 'symbol' => 'Le', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'LRD', 'name' => json_encode(['en' => 'Liberian Dollar']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'CDF', 'name' => json_encode(['en' => 'Congolese Franc']), 'symbol' => 'FC', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'ETB', 'name' => json_encode(['en' => 'Ethiopian Birr']), 'symbol' => 'Br', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'GHS', 'name' => json_encode(['en' => 'Ghanaian Cedi']), 'symbol' => '₵', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'DZD', 'name' => json_encode(['en' => 'Algerian Dinar']), 'symbol' => 'دج', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'MAD', 'name' => json_encode(['en' => 'Moroccan Dirham']), 'symbol' => 'DH', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'TND', 'name' => json_encode(['en' => 'Tunisian Dinar']), 'symbol' => 'د.ت', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 3, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'LYD', 'name' => json_encode(['en' => 'Libyan Dinar']), 'symbol' => 'ل.د', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 3, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SDG', 'name' => json_encode(['en' => 'Sudanese Pound']), 'symbol' => 'ج.س.', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'ZMW', 'name' => json_encode(['en' => 'Zambian Kwacha']), 'symbol' => 'ZK', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'BWP', 'name' => json_encode(['en' => 'Botswana Pula']), 'symbol' => 'P', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'NAD', 'name' => json_encode(['en' => 'Namibian Dollar']), 'symbol' => 'N$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SZL', 'name' => json_encode(['en' => 'Swazi Lilangeni']), 'symbol' => 'L', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'LSL', 'name' => json_encode(['en' => 'Lesotho Loti']), 'symbol' => 'M', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'MZN', 'name' => json_encode(['en' => 'Mozambican Metical']), 'symbol' => 'MT', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'AOA', 'name' => json_encode(['en' => 'Angolan Kwanza']), 'symbol' => 'Kz', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'MWK', 'name' => json_encode(['en' => 'Malawian Kwacha']), 'symbol' => 'MK', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'MUR', 'name' => json_encode(['en' => 'Mauritian Rupee']), 'symbol' => '₨', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SCR', 'name' => json_encode(['en' => 'Seychellois Rupee']), 'symbol' => '₨', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'MVR', 'name' => json_encode(['en' => 'Maldivian Rufiyaa']), 'symbol' => '.ރ', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'MGA', 'name' => json_encode(['en' => 'Malagasy Ariary']), 'symbol' => 'Ar', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'KMF', 'name' => json_encode(['en' => 'Comorian Franc']), 'symbol' => 'CF', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'RWF', 'name' => json_encode(['en' => 'Rwandan Franc']), 'symbol' => 'FRw', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'BIF', 'name' => json_encode(['en' => 'Burundian Franc']), 'symbol' => 'FBu', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'DJF', 'name' => json_encode(['en' => 'Djiboutian Franc']), 'symbol' => 'Fdj', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'SOS', 'name' => json_encode(['en' => 'Somali Shilling']), 'symbol' => 'S', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'ERN', 'name' => json_encode(['en' => 'Eritrean Nakfa']), 'symbol' => 'Nkf', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'XAF', 'name' => json_encode(['en' => 'Central African CFA Franc']), 'symbol' => 'FCFA', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'XOF', 'name' => json_encode(['en' => 'West African CFA Franc']), 'symbol' => 'CFA', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'GNF', 'name' => json_encode(['en' => 'Guinean Franc']), 'symbol' => 'FG', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'after', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'CVE', 'name' => json_encode(['en' => 'Cape Verdean Escudo']), 'symbol' => '$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],
            ['code' => 'STN', 'name' => json_encode(['en' => 'São Tomé and Príncipe Dobra']), 'symbol' => 'Db', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => '.', 'decimal_separator' => ',' ],

            // Caribbean
            ['code' => 'DOP', 'name' => json_encode(['en' => 'Dominican Peso']), 'symbol' => 'RD$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'HTG', 'name' => json_encode(['en' => 'Haitian Gourde']), 'symbol' => 'G', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'BBD', 'name' => json_encode(['en' => 'Barbadian Dollar']), 'symbol' => 'Bds$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'TTD', 'name' => json_encode(['en' => 'Trinidad and Tobago Dollar']), 'symbol' => 'TT$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'XCD', 'name' => json_encode(['en' => 'East Caribbean Dollar']), 'symbol' => 'EC$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'BSD', 'name' => json_encode(['en' => 'Bahamian Dollar']), 'symbol' => 'B$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'KYD', 'name' => json_encode(['en' => 'Cayman Islands Dollar']), 'symbol' => 'CI$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'BMD', 'name' => json_encode(['en' => 'Bermudian Dollar']), 'symbol' => 'BD$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'AWG', 'name' => json_encode(['en' => 'Aruban Florin']), 'symbol' => 'ƒ', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'ANG', 'name' => json_encode(['en' => 'Netherlands Antillean Guilder']), 'symbol' => 'ƒ', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],

            // Pacific
            ['code' => 'FJD', 'name' => json_encode(['en' => 'Fijian Dollar']), 'symbol' => 'FJ$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'PGK', 'name' => json_encode(['en' => 'Papua New Guinean Kina']), 'symbol' => 'K', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'SBD', 'name' => json_encode(['en' => 'Solomon Islands Dollar']), 'symbol' => 'SI$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'TOP', 'name' => json_encode(['en' => 'Tongan Paanga']), 'symbol' => 'T$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'VUV', 'name' => json_encode(['en' => 'Vanuatu Vatu']), 'symbol' => 'VT', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 0, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'WST', 'name' => json_encode(['en' => 'Samoan Tala']), 'symbol' => 'WS$', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'XPF', 'name' => json_encode(['en' => 'CFP Franc']), 'symbol' => '₣', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'NCO', 'name' => json_encode(['en' => 'New Caledonian Franc']), 'symbol' => '₣', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],

            // Special Currencies
            ['code' => 'XDR', 'name' => json_encode(['en' => 'Special Drawing Rights']), 'symbol' => 'SDR', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'XAU', 'name' => json_encode(['en' => 'Gold (troy ounce)']), 'symbol' => 'Au', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'XAG', 'name' => json_encode(['en' => 'Silver (troy ounce)']), 'symbol' => 'Ag', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'XPT', 'name' => json_encode(['en' => 'Platinum (troy ounce)']), 'symbol' => 'Pt', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'XPD', 'name' => json_encode(['en' => 'Palladium (troy ounce)']), 'symbol' => 'Pd', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 2, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            // Cryptocurrencies (major ones)
            ['code' => 'BTC', 'name' => json_encode(['en' => 'Bitcoin']), 'symbol' => '₿', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 8, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'ETH', 'name' => json_encode(['en' => 'Ethereum']), 'symbol' => 'Ξ', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 8, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'LTC', 'name' => json_encode(['en' => 'Litecoin']), 'symbol' => 'Ł', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 8, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.' ],
            ['code' => 'XRP', 'name' => json_encode(['en' => 'Ripple']), 'symbol' => 'XRP', 'is_active' => false, 'is_default' => false, 'is_base' => false, 'decimal_places' => 6, 'symbol_position' => 'before', 'thousands_separator' => ',', 'decimal_separator' => '.'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('currencies');
    }
};
