<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->jsonb('name');
            $table->string('iso_code_2');
            $table->string('iso_code_3');
            $table->boolean('is_active')->default(true);
        });

        \DB::table('countries')->insert([
            array("name" => json_encode(['en' => 'Afghanistan']), "iso_code_2" => 'AF', 'iso_code_3' => 'AFG', 'is_active' => false),
            array("name" => json_encode(['en' => 'Åland Islands']), "iso_code_2" => 'AX', 'iso_code_3' => 'ALA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Albania']), "iso_code_2" => 'AL', 'iso_code_3' => 'ALB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Algeria']), "iso_code_2" => 'DZ', 'iso_code_3' => 'DZA', 'is_active' => false),
            array("name" => json_encode(['en' => 'American Samoa']), "iso_code_2" => 'AS', 'iso_code_3' => 'ASM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Andorra']), "iso_code_2" => 'AD', 'iso_code_3' => 'AND', 'is_active' => false),
            array("name" => json_encode(['en' => 'Angola']), "iso_code_2" => 'AO', 'iso_code_3' => 'AGO', 'is_active' => false),
            array("name" => json_encode(['en' => 'Anguilla']), "iso_code_2" => 'AI', 'iso_code_3' => 'AIA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Antarctica']), "iso_code_2" => 'AQ', 'iso_code_3' => 'ATA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Antigua and Barbuda']), "iso_code_2" => 'AG', 'iso_code_3' => 'ATG', 'is_active' => false),
            array("name" => json_encode(['en' => 'Argentina']), "iso_code_2" => 'AR', 'iso_code_3' => 'ARG', 'is_active' => false),
            array("name" => json_encode(['en' => 'Armenia']), "iso_code_2" => 'AM', 'iso_code_3' => 'ARM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Aruba']), "iso_code_2" => 'AW', 'iso_code_3' => 'ABW', 'is_active' => false),
            array("name" => json_encode(['en' => 'Australia']), "iso_code_2" => 'AU', 'iso_code_3' => 'AUS', 'is_active' => false),
            array("name" => json_encode(['en' => 'Austria']), "iso_code_2" => 'AT', 'iso_code_3' => 'AUT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Azerbaijan']), "iso_code_2" => 'AZ', 'iso_code_3' => 'AZE', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bahamas']), "iso_code_2" => 'BS', 'iso_code_3' => 'BHS', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bahrain']), "iso_code_2" => 'BH', 'iso_code_3' => 'BHR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bangladesh']), "iso_code_2" => 'BD', 'iso_code_3' => 'BGD', 'is_active' => false),
            array("name" => json_encode(['en' => 'Barbados']), "iso_code_2" => 'BB', 'iso_code_3' => 'BRB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Belarus']), "iso_code_2" => 'BY', 'iso_code_3' => 'BLR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Belgium']), "iso_code_2" => 'BE', 'iso_code_3' => 'BEL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Belize']), "iso_code_2" => 'BZ', 'iso_code_3' => 'BLZ', 'is_active' => false),
            array("name" => json_encode(['en' => 'Benin']), "iso_code_2" => 'BJ', 'iso_code_3' => 'BEN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bermuda']), "iso_code_2" => 'BM', 'iso_code_3' => 'BMU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bhutan']), "iso_code_2" => 'BT', 'iso_code_3' => 'BTN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bolivia']), "iso_code_2" => 'BO', 'iso_code_3' => 'BOL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bosnia and Herzegovina']), "iso_code_2" => 'BA', 'iso_code_3' => 'BIH', 'is_active' => true),
            array("name" => json_encode(['en' => 'Botswana']), "iso_code_2" => 'BW', 'iso_code_3' => 'BWA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bouvet Island']), "iso_code_2" => 'BV', 'iso_code_3' => 'BVT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Brazil']), "iso_code_2" => 'BR', 'iso_code_3' => 'BRA', 'is_active' => false),
            array("name" => json_encode(['en' => 'British Indian Ocean Territory']), "iso_code_2" => 'IO', 'iso_code_3' => 'IOT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Brunei Darussalam']), "iso_code_2" => 'BN', 'iso_code_3' => 'BRN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Bulgaria']), "iso_code_2" => 'BG', 'iso_code_3' => 'BGR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Burkina Faso']), "iso_code_2" => 'BF', 'iso_code_3' => 'BFA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Burundi']), "iso_code_2" => 'BI', 'iso_code_3' => 'BDI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Cambodia']), "iso_code_2" => 'KH', 'iso_code_3' => 'KHM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Cameroon']), "iso_code_2" => 'CM', 'iso_code_3' => 'CMR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Canada']), "iso_code_2" => 'CA', 'iso_code_3' => 'CAN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Cape Verde']), "iso_code_2" => 'CV', 'iso_code_3' => 'CPV', 'is_active' => false),
            array("name" => json_encode(['en' => 'Cayman Islands']), "iso_code_2" => 'KY', 'iso_code_3' => 'CYM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Central African Republic']), "iso_code_2" => 'CF', 'iso_code_3' => 'CAF', 'is_active' => false),
            array("name" => json_encode(['en' => 'Chad']), "iso_code_2" => 'TD', 'iso_code_3' => 'TCD', 'is_active' => false),
            array("name" => json_encode(['en' => 'Chile']), "iso_code_2" => 'CL', 'iso_code_3' => 'CHL', 'is_active' => false),
            array("name" => json_encode(['en' => 'China']), "iso_code_2" => 'CN', 'iso_code_3' => 'CHN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Christmas Island']), "iso_code_2" => 'CX', 'iso_code_3' => 'CXR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Cocos (Keeling) Islands']), "iso_code_2" => 'CC', 'iso_code_3' => 'CCK', 'is_active' => false),
            array("name" => json_encode(['en' => 'Colombia']), "iso_code_2" => 'CO', 'iso_code_3' => 'COL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Comoros']), "iso_code_2" => 'KM', 'iso_code_3' => 'COM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Congo']), "iso_code_2" => 'CG', 'iso_code_3' => 'COG', 'is_active' => false),
            array("name" => json_encode(['en' => 'Congo, The Democratic Republic of the']), "iso_code_2" => 'CD', 'iso_code_3' => 'COD', 'is_active' => false),
            array("name" => json_encode(['en' => 'Cook Islands']), "iso_code_2" => 'CK', 'iso_code_3' => 'CKI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Costa Rica']), "iso_code_2" => 'CR', 'iso_code_3' => 'CRI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Cote D\'Ivoire']), "iso_code_2" => 'CI', 'iso_code_3' => 'CIV', 'is_active' => false),
            array("name" => json_encode(['en' => 'Croatia']), "iso_code_2" => 'HR', 'iso_code_3' => 'HRV', 'is_active' => true),
            array("name" => json_encode(['en' => 'Cuba']), "iso_code_2" => 'CU', 'iso_code_3' => 'CUB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Cyprus']), "iso_code_2" => 'CY', 'iso_code_3' => 'CYP', 'is_active' => false),
            array("name" => json_encode(['en' => 'Czech Republic']), "iso_code_2" => 'CZ', 'iso_code_3' => 'CZE', 'is_active' => false),
            array("name" => json_encode(['en' => 'Denmark']), "iso_code_2" => 'DK', 'iso_code_3' => 'DNK', 'is_active' => false),
            array("name" => json_encode(['en' => 'Djibouti']), "iso_code_2" => 'DJ', 'iso_code_3' => 'DJI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Dominica']), "iso_code_2" => 'DM', 'iso_code_3' => 'DMA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Dominican Republic']), "iso_code_2" => 'DO', 'iso_code_3' => 'DOM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Ecuador']), "iso_code_2" => 'EC', 'iso_code_3' => 'ECU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Egypt']), "iso_code_2" => 'EG', 'iso_code_3' => 'EGY', 'is_active' => false),
            array("name" => json_encode(['en' => 'El Salvador']), "iso_code_2" => 'SV', 'iso_code_3' => 'SLV', 'is_active' => false),
            array("name" => json_encode(['en' => 'Equatorial Guinea']), "iso_code_2" => 'GQ', 'iso_code_3' => 'GNQ', 'is_active' => false),
            array("name" => json_encode(['en' => 'Eritrea']), "iso_code_2" => 'ER', 'iso_code_3' => 'ERI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Estonia']), "iso_code_2" => 'EE', 'iso_code_3' => 'EST', 'is_active' => false),
            array("name" => json_encode(['en' => 'Ethiopia']), "iso_code_2" => 'ET', 'iso_code_3' => 'ETH', 'is_active' => false),
            array("name" => json_encode(['en' => 'Falkland Islands (Malvinas)']), "iso_code_2" => 'FK', 'iso_code_3' => 'FLK', 'is_active' => false),
            array("name" => json_encode(['en' => 'Faroe Islands']), "iso_code_2" => 'FO', 'iso_code_3' => 'FRO', 'is_active' => false),
            array("name" => json_encode(['en' => 'Fiji']), "iso_code_2" => 'FJ', 'iso_code_3' => 'FJI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Finland']), "iso_code_2" => 'FI', 'iso_code_3' => 'FIN', 'is_active' => false),
            array("name" => json_encode(['en' => 'France']), "iso_code_2" => 'FR', 'iso_code_3' => 'FRA', 'is_active' => false),
            array("name" => json_encode(['en' => 'French Guiana']), "iso_code_2" => 'GF', 'iso_code_3' => 'GUF', 'is_active' => false),
            array("name" => json_encode(['en' => 'French Polynesia']), "iso_code_2" => 'PF', 'iso_code_3' => 'PYF', 'is_active' => false),
            array("name" => json_encode(['en' => 'French Southern Territories']), "iso_code_2" => 'TF', 'iso_code_3' => 'ATF', 'is_active' => false),
            array("name" => json_encode(['en' => 'Gabon']), "iso_code_2" => 'GA', 'iso_code_3' => 'GAB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Gambia']), "iso_code_2" => 'GM', 'iso_code_3' => 'GMB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Georgia']), "iso_code_2" => 'GE', 'iso_code_3' => 'GEO', 'is_active' => false),
            array("name" => json_encode(['en' => 'Germany']), "iso_code_2" => 'DE', 'iso_code_3' => 'DEU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Ghana']), "iso_code_2" => 'GH', 'iso_code_3' => 'GHA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Gibraltar']), "iso_code_2" => 'GI', 'iso_code_3' => 'GIB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Greece']), "iso_code_2" => 'GR', 'iso_code_3' => 'GRC', 'is_active' => false),
            array("name" => json_encode(['en' => 'Greenland']), "iso_code_2" => 'GL', 'iso_code_3' => 'GRL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Grenada']), "iso_code_2" => 'GD', 'iso_code_3' => 'GRD', 'is_active' => false),
            array("name" => json_encode(['en' => 'Guadeloupe']), "iso_code_2" => 'GP', 'iso_code_3' => 'GLP', 'is_active' => false),
            array("name" => json_encode(['en' => 'Guam']), "iso_code_2" => 'GU', 'iso_code_3' => 'GUM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Guatemala']), "iso_code_2" => 'GT', 'iso_code_3' => 'GTM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Guernsey']), "iso_code_2" => 'GG', 'iso_code_3' => 'GGY', 'is_active' => false),
            array("name" => json_encode(['en' => 'Guinea']), "iso_code_2" => 'GN', 'iso_code_3' => 'GIN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Guinea-Bissau']), "iso_code_2" => 'GW', 'iso_code_3' => 'GNB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Guyana']), "iso_code_2" => 'GY', 'iso_code_3' => 'GUY', 'is_active' => false),
            array("name" => json_encode(['en' => 'Haiti']), "iso_code_2" => 'HT', 'iso_code_3' => 'HTI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Heard Island and Mcdonald Islands']), "iso_code_2" => 'HM', 'iso_code_3' => 'HMD', 'is_active' => false),
            array("name" => json_encode(['en' => 'Holy See (Vatican City State)']), "iso_code_2" => 'VA', 'iso_code_3' => 'VAT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Honduras']), "iso_code_2" => 'HN', 'iso_code_3' => 'HND', 'is_active' => false),
            array("name" => json_encode(['en' => 'Hong Kong']), "iso_code_2" => 'HK', 'iso_code_3' => 'HKG', 'is_active' => false),
            array("name" => json_encode(['en' => 'Hungary']), "iso_code_2" => 'HU', 'iso_code_3' => 'HUN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Iceland']), "iso_code_2" => 'IS', 'iso_code_3' => 'ISL', 'is_active' => false),
            array("name" => json_encode(['en' => 'India']), "iso_code_2" => 'IN', 'iso_code_3' => 'IND', 'is_active' => false),
            array("name" => json_encode(['en' => 'Indonesia']), "iso_code_2" => 'ID', 'iso_code_3' => 'IDN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Iran, Islamic Republic Of']), "iso_code_2" => 'IR', 'iso_code_3' => 'IRN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Iraq']), "iso_code_2" => 'IQ', 'iso_code_3' => 'IRQ', 'is_active' => false),
            array("name" => json_encode(['en' => 'Ireland']), "iso_code_2" => 'IE', 'iso_code_3' => 'IRL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Isle of Man']), "iso_code_2" => 'IM', 'iso_code_3' => 'IMN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Israel']), "iso_code_2" => 'IL', 'iso_code_3' => 'ISR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Italy']), "iso_code_2" => 'IT', 'iso_code_3' => 'ITA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Jamaica']), "iso_code_2" => 'JM', 'iso_code_3' => 'JAM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Japan']), "iso_code_2" => 'JP', 'iso_code_3' => 'JPN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Jersey']), "iso_code_2" => 'JE', 'iso_code_3' => 'JEY', 'is_active' => false),
            array("name" => json_encode(['en' => 'Jordan']), "iso_code_2" => 'JO', 'iso_code_3' => 'JOR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Kazakhstan']), "iso_code_2" => 'KZ', 'iso_code_3' => 'KAZ', 'is_active' => false),
            array("name" => json_encode(['en' => 'Kenya']), "iso_code_2" => 'KE', 'iso_code_3' => 'KEN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Kiribati']), "iso_code_2" => 'KI', 'iso_code_3' => 'KIR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Korea, Democratic People\'S Republic of']), "iso_code_2" => 'KP', 'iso_code_3' => 'KOR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Korea, Republic of']), "iso_code_2" => 'KR', 'iso_code_3' => 'KOR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Kuwait']), "iso_code_2" => 'KW', 'iso_code_3' => 'KWT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Kyrgyzstan']), "iso_code_2" => 'KG', 'iso_code_3' => 'KGZ', 'is_active' => false),
            array("name" => json_encode(['en' => 'Laos']), "iso_code_2" => 'LA', 'iso_code_3' => 'LAO', 'is_active' => false),
            array("name" => json_encode(['en' => 'Latvia']), "iso_code_2" => 'LV', 'iso_code_3' => 'LVA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Lebanon']), "iso_code_2" => 'LB', 'iso_code_3' => 'LBN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Lesotho']), "iso_code_2" => 'LS', 'iso_code_3' => 'LSO', 'is_active' => false),
            array("name" => json_encode(['en' => 'Liberia']), "iso_code_2" => 'LR', 'iso_code_3' => 'LBR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Libya']), "iso_code_2" => 'LY', 'iso_code_3' => 'LBY', 'is_active' => false),
            array("name" => json_encode(['en' => 'Liechtenstein']), "iso_code_2" => 'LI', 'iso_code_3' => 'LIE', 'is_active' => false),
            array("name" => json_encode(['en' => 'Lithuania']), "iso_code_2" => 'LT', 'iso_code_3' => 'LTU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Luxembourg']), "iso_code_2" => 'LU', 'iso_code_3' => 'LUX', 'is_active' => false),
            array("name" => json_encode(['en' => 'Macao']), "iso_code_2" => 'MO', 'iso_code_3' => 'MAC', 'is_active' => false),
            array("name" => json_encode(['en' => 'North Macedonia']), "iso_code_2" => 'MK', 'iso_code_3' => 'MKD', 'is_active' => false),
            array("name" => json_encode(['en' => 'Madagascar']), "iso_code_2" => 'MG', 'iso_code_3' => 'MDG', 'is_active' => false),
            array("name" => json_encode(['en' => 'Malawi']), "iso_code_2" => 'MW', 'iso_code_3' => 'MWI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Malaysia']), "iso_code_2" => 'MY', 'iso_code_3' => 'MYS', 'is_active' => false),
            array("name" => json_encode(['en' => 'Maldives']), "iso_code_2" => 'MV', 'iso_code_3' => 'MDV', 'is_active' => false),
            array("name" => json_encode(['en' => 'Mali']), "iso_code_2" => 'ML', 'iso_code_3' => 'MLI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Malta']), "iso_code_2" => 'MT', 'iso_code_3' => 'MLT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Marshall Islands']), "iso_code_2" => 'MH', 'iso_code_3' => 'MHL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Martinique']), "iso_code_2" => 'MQ', 'iso_code_3' => 'MTQ', 'is_active' => false),
            array("name" => json_encode(['en' => 'Mauritania']), "iso_code_2" => 'MR', 'iso_code_3' => 'MRT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Mauritius']), "iso_code_2" => 'MU', 'iso_code_3' => 'MUS', 'is_active' => false),
            array("name" => json_encode(['en' => 'Mayotte']), "iso_code_2" => 'YT', 'iso_code_3' => 'MYT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Mexico']), "iso_code_2" => 'MX', 'iso_code_3' => 'MEX', 'is_active' => false),
            array("name" => json_encode(['en' => 'Micronesia, Federated States of']), "iso_code_2" => 'FM', 'iso_code_3' => 'FSM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Moldova, Republic of']), "iso_code_2" => 'MD', 'iso_code_3' => 'MDA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Monaco']), "iso_code_2" => 'MC', 'iso_code_3' => 'MCO', 'is_active' => false),
            array("name" => json_encode(['en' => 'Mongolia']), "iso_code_2" => 'MN', 'iso_code_3' => 'MNG', 'is_active' => false),
            array("name" => json_encode(['en' => 'Montserrat']), "iso_code_2" => 'MS', 'iso_code_3' => 'MSR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Morocco']), "iso_code_2" => 'MA', 'iso_code_3' => 'MAR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Mozambique']), "iso_code_2" => 'MZ', 'iso_code_3' => 'MOZ', 'is_active' => false),
            array("name" => json_encode(['en' => 'Myanmar']), "iso_code_2" => 'MM', 'iso_code_3' => 'MMR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Namibia']), "iso_code_2" => 'NA', 'iso_code_3' => 'NAM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Nauru']), "iso_code_2" => 'NR', 'iso_code_3' => 'NRU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Nepal']), "iso_code_2" => 'NP', 'iso_code_3' => 'NPL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Netherlands']), "iso_code_2" => 'NL', 'iso_code_3' => 'NLD', 'is_active' => false),
            array("name" => json_encode(['en' => 'Netherlands Antilles']), "iso_code_2" => 'AN', 'iso_code_3' => 'ANT', 'is_active' => false),
            array("name" => json_encode(['en' => 'New Caledonia']), "iso_code_2" => 'NC', 'iso_code_3' => 'NCL', 'is_active' => false),
            array("name" => json_encode(['en' => 'New Zealand']), "iso_code_2" => 'NZ', 'iso_code_3' => 'NZL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Nicaragua']), "iso_code_2" => 'NI', 'iso_code_3' => 'NIC', 'is_active' => false),
            array("name" => json_encode(['en' => 'Niger']), "iso_code_2" => 'NE', 'iso_code_3' => 'NER', 'is_active' => false),
            array("name" => json_encode(['en' => 'Nigeria']), "iso_code_2" => 'NG', 'iso_code_3' => 'NGA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Niue']), "iso_code_2" => 'NU', 'iso_code_3' => 'NIU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Norfolk Island']), "iso_code_2" => 'NF', 'iso_code_3' => 'NFK', 'is_active' => false),
            array("name" => json_encode(['en' => 'Northern Mariana Islands']), "iso_code_2" => 'MP', 'iso_code_3' => 'MNP', 'is_active' => false),
            array("name" => json_encode(['en' => 'Norway']), "iso_code_2" => 'NO', 'iso_code_3' => 'NOR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Oman']), "iso_code_2" => 'OM', 'iso_code_3' => 'OMN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Pakistan']), "iso_code_2" => 'PK', 'iso_code_3' => 'PAK', 'is_active' => false),
            array("name" => json_encode(['en' => 'Palau']), "iso_code_2" => 'PW', 'iso_code_3' => 'PLW', 'is_active' => false),
            array("name" => json_encode(['en' => 'Palestine']), "iso_code_2" => 'PS', 'iso_code_3' => 'PSE', 'is_active' => false),
            array("name" => json_encode(['en' => 'Panama']), "iso_code_2" => 'PA', 'iso_code_3' => 'PAN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Papua New Guinea']), "iso_code_2" => 'PG', 'iso_code_3' => 'PNG', 'is_active' => false),
            array("name" => json_encode(['en' => 'Paraguay']), "iso_code_2" => 'PY', 'iso_code_3' => 'PRY', 'is_active' => false),
            array("name" => json_encode(['en' => 'Peru']), "iso_code_2" => 'PE', 'iso_code_3' => 'PER', 'is_active' => false),
            array("name" => json_encode(['en' => 'Philippines']), "iso_code_2" => 'PH', 'iso_code_3' => 'PHL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Pitcairn']), "iso_code_2" => 'PN', 'iso_code_3' => 'PCN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Poland']), "iso_code_2" => 'PL', 'iso_code_3' => 'POL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Portugal']), "iso_code_2" => 'PT', 'iso_code_3' => 'PRT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Puerto Rico']), "iso_code_2" => 'PR', 'iso_code_3' => 'PRI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Qatar']), "iso_code_2" => 'QA', 'iso_code_3' => 'QAT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Reunion']), "iso_code_2" => 'RE', 'iso_code_3' => 'REU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Romania']), "iso_code_2" => 'RO', 'iso_code_3' => 'ROU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Russian Federation']), "iso_code_2" => 'RU', 'iso_code_3' => 'RUS', 'is_active' => false),
            array("name" => json_encode(['en' => 'Rwanda']), "iso_code_2" => 'RW', 'iso_code_3' => 'RWA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Saint Helena']), "iso_code_2" => 'SH', 'iso_code_3' => 'SHN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Saint Kitts and Nevis']), "iso_code_2" => 'KN', 'iso_code_3' => 'KNA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Saint Lucia']), "iso_code_2" => 'LC', 'iso_code_3' => 'LCA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Saint Pierre and Miquelon']), "iso_code_2" => 'PM', 'iso_code_3' => 'SPM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Saint Vincent and the Grenadines']), "iso_code_2" => 'VC', 'iso_code_3' => 'VCT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Samoa']), "iso_code_2" => 'WS', 'iso_code_3' => 'WSM', 'is_active' => false),
            array("name" => json_encode(['en' => 'San Marino']), "iso_code_2" => 'SM', 'iso_code_3' => 'SMR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Sao Tome and Principe']), "iso_code_2" => 'ST', 'iso_code_3' => 'STP', 'is_active' => false),
            array("name" => json_encode(['en' => 'Saudi Arabia']), "iso_code_2" => 'SA', 'iso_code_3' => 'SAU', 'is_active' => false),
            array("name" => json_encode(['en' => 'Senegal']), "iso_code_2" => 'SN', 'iso_code_3' => 'SEN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Serbia']), "iso_code_2" => 'RS', 'iso_code_3' => 'SRB', 'is_active' => true),
            array("name" => json_encode(['en' => 'Seychelles']), "iso_code_2" => 'SC', 'iso_code_3' => 'SYC', 'is_active' => false),
            array("name" => json_encode(['en' => 'Sierra Leone']), "iso_code_2" => 'SL', 'iso_code_3' => 'SLE', 'is_active' => false),
            array("name" => json_encode(['en' => 'Singapore']), "iso_code_2" => 'SG', 'iso_code_3' => 'SGP', 'is_active' => false),
            array("name" => json_encode(['en' => 'Slovakia']), "iso_code_2" => 'SK', 'iso_code_3' => 'SVK', 'is_active' => false),
            array("name" => json_encode(['en' => 'Slovenia']), "iso_code_2" => 'SI', 'iso_code_3' => 'SVN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Solomon Islands']), "iso_code_2" => 'SB', 'iso_code_3' => 'SLB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Somalia']), "iso_code_2" => 'SO', 'iso_code_3' => 'SOM', 'is_active' => false),
            array("name" => json_encode(['en' => 'South Africa']), "iso_code_2" => 'ZA', 'iso_code_3' => 'ZAF', 'is_active' => false),
            array("name" => json_encode(['en' => 'South Georgia and the South Sandwich Islands']), "iso_code_2" => 'GS', 'iso_code_3' => 'SGS', 'is_active' => false),
            array("name" => json_encode(['en' => 'Spain']), "iso_code_2" => 'ES', 'iso_code_3' => 'ESP', 'is_active' => false),
            array("name" => json_encode(['en' => 'Sri Lanka']), "iso_code_2" => 'LK', 'iso_code_3' => 'LKA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Sudan']), "iso_code_2" => 'SD', 'iso_code_3' => 'SDN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Suriname']), "iso_code_2" => 'SR', 'iso_code_3' => 'SUR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Svalbard and Jan Mayen']), "iso_code_2" => 'SJ', 'iso_code_3' => 'SJM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Swaziland']), "iso_code_2" => 'SZ', 'iso_code_3' => 'SWZ', 'is_active' => false),
            array("name" => json_encode(['en' => 'Sweden']), "iso_code_2" => 'SE', 'iso_code_3' => 'SWE', 'is_active' => false),
            array("name" => json_encode(['en' => 'Switzerland']), "iso_code_2" => 'CH', 'iso_code_3' => 'CHE', 'is_active' => false),
            array("name" => json_encode(['en' => 'Syria']), "iso_code_2" => 'SY', 'iso_code_3' => 'SYR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Taiwan, Province of China']), "iso_code_2" => 'TW', 'iso_code_3' => 'TWN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Tajikistan']), "iso_code_2" => 'TJ', 'iso_code_3' => 'TJK', 'is_active' => false),
            array("name" => json_encode(['en' => 'Tanzania, United Republic of']), "iso_code_2" => 'TZ', 'iso_code_3' => 'TZA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Thailand']), "iso_code_2" => 'TH', 'iso_code_3' => 'THA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Timor-Leste']), "iso_code_2" => 'TL', 'iso_code_3' => 'TLS', 'is_active' => false),
            array("name" => json_encode(['en' => 'Togo']), "iso_code_2" => 'TG', 'iso_code_3' => 'TGO', 'is_active' => false),
            array("name" => json_encode(['en' => 'Tokelau']), "iso_code_2" => 'TK', 'iso_code_3' => 'TKL', 'is_active' => false),
            array("name" => json_encode(['en' => 'Tonga']), "iso_code_2" => 'TO', 'iso_code_3' => 'TON', 'is_active' => false),
            array("name" => json_encode(['en' => 'Trinidad and Tobago']), "iso_code_2" => 'TT', 'iso_code_3' => 'TTO', 'is_active' => false),
            array("name" => json_encode(['en' => 'Tunisia']), "iso_code_2" => 'TN', 'iso_code_3' => 'TUN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Turkey']), "iso_code_2" => 'TR', 'iso_code_3' => 'TUR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Turkmenistan']), "iso_code_2" => 'TM', 'iso_code_3' => 'TKM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Turks and Caicos Islands']), "iso_code_2" => 'TC', 'iso_code_3' => 'TCA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Tuvalu']), "iso_code_2" => 'TV', 'iso_code_3' => 'TUV', 'is_active' => false),
            array("name" => json_encode(['en' => 'Uganda']), "iso_code_2" => 'UG', 'iso_code_3' => 'UGA', 'is_active' => false),
            array("name" => json_encode(['en' => 'Ukraine']), "iso_code_2" => 'UA', 'iso_code_3' => 'UKR', 'is_active' => false),
            array("name" => json_encode(['en' => 'United Arab Emirates']), "iso_code_2" => 'AE', 'iso_code_3' => 'ARE', 'is_active' => false),
            array("name" => json_encode(['en' => 'United Kingdom']), "iso_code_2" => 'GB', 'iso_code_3' => 'GBR', 'is_active' => false),
            array("name" => json_encode(['en' => 'United States']), "iso_code_2" => 'US', 'iso_code_3' => 'USA', 'is_active' => false),
            array("name" => json_encode(['en' => 'United States Minor Outlying Islands']), "iso_code_2" => 'UM', 'iso_code_3' => 'UMI', 'is_active' => false),
            array("name" => json_encode(['en' => 'Uruguay']), "iso_code_2" => 'UY', 'iso_code_3' => 'URY', 'is_active' => false),
            array("name" => json_encode(['en' => 'Uzbekistan']), "iso_code_2" => 'UZ', 'iso_code_3' => 'UZB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Vanuatu']), "iso_code_2" => 'VU', 'iso_code_3' => 'VUT', 'is_active' => false),
            array("name" => json_encode(['en' => 'Venezuela']), "iso_code_2" => 'VE', 'iso_code_3' => 'VEN', 'is_active' => false),
            array("name" => json_encode(['en' => 'Vietnam']), "iso_code_2" => 'VN', 'iso_code_3' => 'VNM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Virgin Islands, British']), "iso_code_2" => 'VG', 'iso_code_3' => 'VGB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Virgin Islands, U.S.']), "iso_code_2" => 'VI', 'iso_code_3' => 'VIR', 'is_active' => false),
            array("name" => json_encode(['en' => 'Wallis and Futuna']), "iso_code_2" => 'WF', 'iso_code_3' => 'WLF', 'is_active' => false),
            array("name" => json_encode(['en' => 'Western Sahara']), "iso_code_2" => 'EH', 'iso_code_3' => 'ESH', 'is_active' => false),
            array("name" => json_encode(['en' => 'Yemen']), "iso_code_2" => 'YE', 'iso_code_3' => 'YEM', 'is_active' => false),
            array("name" => json_encode(['en' => 'Zambia']), "iso_code_2" => 'ZM', 'iso_code_3' => 'ZMB', 'is_active' => false),
            array("name" => json_encode(['en' => 'Zimbabwe']), "iso_code_2" => 'ZW', 'iso_code_3' => 'ZWE', 'is_active' => false),
            array("name" => json_encode(['en' => 'Montenegro']), "iso_code_2" => 'ME', 'iso_code_3' => 'MNE', 'is_active' => true),
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
