<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('languages', function (Blueprint $table) {
            $table->id();
            $table->jsonb('name');
            $table->string('iso_code')->index();
            $table->boolean('is_active')->default(true);
        });

        \DB::table('languages')->insert([
            ['name' => json_encode(['en' => 'Abkhazian']), 'iso_code' => 'ab', 'is_active' => true],
            ['name' => json_encode(['en' => 'Afar']), 'iso_code' => 'aa', 'is_active' => true],
            ['name' => json_encode(['en' => 'Afrikaans']), 'iso_code' => 'af', 'is_active' => true],
            ['name' => json_encode(['en' => 'Albanian']), 'iso_code' => 'sq', 'is_active' => true],
            ['name' => json_encode(['en' => 'Amharic']), 'iso_code' => 'am', 'is_active' => true],
            ['name' => json_encode(['en' => 'Arabic']), 'iso_code' => 'ar', 'is_active' => true],
            ['name' => json_encode(['en' => 'Aragonese']), 'iso_code' => 'an', 'is_active' => true],
            ['name' => json_encode(['en' => 'Armenian']), 'iso_code' => 'hy', 'is_active' => true],
            ['name' => json_encode(['en' => 'Assamese']), 'iso_code' => 'as', 'is_active' => true],
            ['name' => json_encode(['en' => 'Avestan']), 'iso_code' => 'ae', 'is_active' => true],
            ['name' => json_encode(['en' => 'Aymara']), 'iso_code' => 'ay', 'is_active' => true],
            ['name' => json_encode(['en' => 'Azerbaijani']), 'iso_code' => 'az', 'is_active' => true],
            ['name' => json_encode(['en' => 'Bashkir']), 'iso_code' => 'ba', 'is_active' => true],
            ['name' => json_encode(['en' => 'Basque']), 'iso_code' => 'eu', 'is_active' => true],
            ['name' => json_encode(['en' => 'Belarusian']), 'iso_code' => 'be', 'is_active' => true],
            ['name' => json_encode(['en' => 'Bengali']), 'iso_code' => 'bn', 'is_active' => true],
            ['name' => json_encode(['en' => 'Bihari']), 'iso_code' => 'bh', 'is_active' => true],
            ['name' => json_encode(['en' => 'Bislama']), 'iso_code' => 'bi', 'is_active' => true],
            ['name' => json_encode(['en' => 'Bosnian']), 'iso_code' => 'bs', 'is_active' => true],
            ['name' => json_encode(['en' => 'Breton']), 'iso_code' => 'br', 'is_active' => true],
            ['name' => json_encode(['en' => 'Bulgarian']), 'iso_code' => 'bg', 'is_active' => true],
            ['name' => json_encode(['en' => 'Burmese']), 'iso_code' => 'my', 'is_active' => true],
            ['name' => json_encode(['en' => 'Catalan']), 'iso_code' => 'ca', 'is_active' => true],
            ['name' => json_encode(['en' => 'Chamorro']), 'iso_code' => 'ch', 'is_active' => true],
            ['name' => json_encode(['en' => 'Chechen']), 'iso_code' => 'ce', 'is_active' => true],
            ['name' => json_encode(['en' => 'Chinese']), 'iso_code' => 'zh', 'is_active' => true],
            ['name' => json_encode(['en' => 'Church Slavic; Slavonic; Old Bulgarian']), 'iso_code' => 'cu', 'is_active' => true],
            ['name' => json_encode(['en' => 'Chuvash']), 'iso_code' => 'cv', 'is_active' => true],
            ['name' => json_encode(['en' => 'Cornish']), 'iso_code' => 'kw', 'is_active' => true],
            ['name' => json_encode(['en' => 'Corsican']), 'iso_code' => 'co', 'is_active' => true],
            ['name' => json_encode(['en' => 'Croatian']), 'iso_code' => 'hr', 'is_active' => true],
            ['name' => json_encode(['en' => 'Czech']), 'iso_code' => 'cs', 'is_active' => true],
            ['name' => json_encode(['en' => 'Danish']), 'iso_code' => 'da', 'is_active' => true],
            ['name' => json_encode(['en' => 'Divehi; Dhivehi; Maldivian']), 'iso_code' => 'dv', 'is_active' => true],
            ['name' => json_encode(['en' => 'Dutch']), 'iso_code' => 'nl', 'is_active' => true],
            ['name' => json_encode(['en' => 'Dzongkha']), 'iso_code' => 'dz', 'is_active' => true],
            ['name' => json_encode(['en' => 'English']), 'iso_code' => 'en', 'is_active' => true],
            ['name' => json_encode(['en' => 'Esperanto']), 'iso_code' => 'eo', 'is_active' => true],
            ['name' => json_encode(['en' => 'Estonian']), 'iso_code' => 'et', 'is_active' => true],
            ['name' => json_encode(['en' => 'Faroese']), 'iso_code' => 'fo', 'is_active' => true],
            ['name' => json_encode(['en' => 'Fijian']), 'iso_code' => 'fj', 'is_active' => true],
            ['name' => json_encode(['en' => 'Finnish']), 'iso_code' => 'fi', 'is_active' => true],
            ['name' => json_encode(['en' => 'French']), 'iso_code' => 'fr', 'is_active' => true],
            ['name' => json_encode(['en' => 'Gaelic; Scottish Gaelic']), 'iso_code' => 'gd', 'is_active' => true],
            ['name' => json_encode(['en' => 'Galician']), 'iso_code' => 'gl', 'is_active' => true],
            ['name' => json_encode(['en' => 'Georgian']), 'iso_code' => 'ka', 'is_active' => true],
            ['name' => json_encode(['en' => 'German']), 'iso_code' => 'de', 'is_active' => true],
            ['name' => json_encode(['en' => 'Greek, Modern (1453-)']), 'iso_code' => 'el', 'is_active' => true],
            ['name' => json_encode(['en' => 'Guarani']), 'iso_code' => 'gn', 'is_active' => true],
            ['name' => json_encode(['en' => 'Gujarati']), 'iso_code' => 'gu', 'is_active' => true],
            ['name' => json_encode(['en' => 'Haitian; Haitian Creole']), 'iso_code' => 'ht', 'is_active' => true],
            ['name' => json_encode(['en' => 'Hausa']), 'iso_code' => 'ha', 'is_active' => true],
            ['name' => json_encode(['en' => 'Hebrew']), 'iso_code' => 'he', 'is_active' => true],
            ['name' => json_encode(['en' => 'Herero']), 'iso_code' => 'hz', 'is_active' => true],
            ['name' => json_encode(['en' => 'Hindi']), 'iso_code' => 'hi', 'is_active' => true],
            ['name' => json_encode(['en' => 'Hiri Motu']), 'iso_code' => 'ho', 'is_active' => true],
            ['name' => json_encode(['en' => 'Hungarian']), 'iso_code' => 'hu', 'is_active' => true],
            ['name' => json_encode(['en' => 'Icelandic']), 'iso_code' => 'is', 'is_active' => true],
            ['name' => json_encode(['en' => 'Ido']), 'iso_code' => 'io', 'is_active' => true],
            ['name' => json_encode(['en' => 'Indonesian']), 'iso_code' => 'id', 'is_active' => true],
            ['name' => json_encode(['en' => 'Interlingue']), 'iso_code' => 'ie', 'is_active' => true],
            ['name' => json_encode(['en' => 'Inuktitut']), 'iso_code' => 'iu', 'is_active' => true],
            ['name' => json_encode(['en' => 'Inupiaq']), 'iso_code' => 'ik', 'is_active' => true],
            ['name' => json_encode(['en' => 'Irish']), 'iso_code' => 'ga', 'is_active' => true],
            ['name' => json_encode(['en' => 'Italian']), 'iso_code' => 'it', 'is_active' => true],
            ['name' => json_encode(['en' => 'Japanese']), 'iso_code' => 'ja', 'is_active' => true],
            ['name' => json_encode(['en' => 'Javanese']), 'iso_code' => 'jv', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kalaallisut']), 'iso_code' => 'kl', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kannada']), 'iso_code' => 'kn', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kashmiri']), 'iso_code' => 'ks', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kazakh']), 'iso_code' => 'kk', 'is_active' => true],
            ['name' => json_encode(['en' => 'Khmer']), 'iso_code' => 'km', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kikuyu; Gikuyu']), 'iso_code' => 'ki', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kinyarwanda']), 'iso_code' => 'rw', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kirghiz']), 'iso_code' => 'ky', 'is_active' => true],
            ['name' => json_encode(['en' => 'Komi']), 'iso_code' => 'kv', 'is_active' => true],
            ['name' => json_encode(['en' => 'Korean']), 'iso_code' => 'ko', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kuanyama; Kwanyama']), 'iso_code' => 'kj', 'is_active' => true],
            ['name' => json_encode(['en' => 'Kurdish']), 'iso_code' => 'ku', 'is_active' => true],
            ['name' => json_encode(['en' => 'Lao']), 'iso_code' => 'lo', 'is_active' => true],
            ['name' => json_encode(['en' => 'Latin']), 'iso_code' => 'la', 'is_active' => true],
            ['name' => json_encode(['en' => 'Latvian']), 'iso_code' => 'lv', 'is_active' => true],
            ['name' => json_encode(['en' => 'Limburgan; Limburger; Limburgish']), 'iso_code' => 'li', 'is_active' => true],
            ['name' => json_encode(['en' => 'Lingala']), 'iso_code' => 'ln', 'is_active' => true],
            ['name' => json_encode(['en' => 'Lithuanian']), 'iso_code' => 'lt', 'is_active' => true],
            ['name' => json_encode(['en' => 'Luxembourgish; Letzeburgesch']), 'iso_code' => 'lb', 'is_active' => true],
            ['name' => json_encode(['en' => 'Macedonian']), 'iso_code' => 'mk', 'is_active' => true],
            ['name' => json_encode(['en' => 'Malagasy']), 'iso_code' => 'mg', 'is_active' => true],
            ['name' => json_encode(['en' => 'Malay']), 'iso_code' => 'ms', 'is_active' => true],
            ['name' => json_encode(['en' => 'Malayalam']), 'iso_code' => 'ml', 'is_active' => true],
            ['name' => json_encode(['en' => 'Maltese']), 'iso_code' => 'mt', 'is_active' => true],
            ['name' => json_encode(['en' => 'Manx']), 'iso_code' => 'gv', 'is_active' => true],
            ['name' => json_encode(['en' => 'Maori']), 'iso_code' => 'mi', 'is_active' => true],
            ['name' => json_encode(['en' => 'Marathi']), 'iso_code' => 'mr', 'is_active' => true],
            ['name' => json_encode(['en' => 'Marshallese']), 'iso_code' => 'mh', 'is_active' => true],
            ['name' => json_encode(['en' => 'Moldavian']), 'iso_code' => 'mo', 'is_active' => true],
            ['name' => json_encode(['en' => 'Mongolian']), 'iso_code' => 'mn', 'is_active' => true],
            ['name' => json_encode(['en' => 'Nauru']), 'iso_code' => 'na', 'is_active' => true],
            ['name' => json_encode(['en' => 'Navaho, Navajo']), 'iso_code' => 'nv', 'is_active' => true],
            ['name' => json_encode(['en' => 'Ndebele, North']), 'iso_code' => 'nd', 'is_active' => true],
            ['name' => json_encode(['en' => 'Ndebele, South']), 'iso_code' => 'nr', 'is_active' => true],
            ['name' => json_encode(['en' => 'Ndonga']), 'iso_code' => 'ng', 'is_active' => true],
            ['name' => json_encode(['en' => 'Nepali']), 'iso_code' => 'ne', 'is_active' => true],
            ['name' => json_encode(['en' => 'Northern Sami']), 'iso_code' => 'se', 'is_active' => true],
            ['name' => json_encode(['en' => 'Norwegian']), 'iso_code' => 'no', 'is_active' => true],
            ['name' => json_encode(['en' => 'Norwegian Bokmal']), 'iso_code' => 'nb', 'is_active' => true],
            ['name' => json_encode(['en' => 'Norwegian Nynorsk']), 'iso_code' => 'nn', 'is_active' => true],
            ['name' => json_encode(['en' => 'Nyanja; Chichewa; Chewa']), 'iso_code' => 'ny', 'is_active' => true],
            ['name' => json_encode(['en' => 'Occitan (post 1500); Provencal']), 'iso_code' => 'oc', 'is_active' => true],
            ['name' => json_encode(['en' => 'Oriya']), 'iso_code' => 'or', 'is_active' => true],
            ['name' => json_encode(['en' => 'Oromo']), 'iso_code' => 'om', 'is_active' => true],
            ['name' => json_encode(['en' => 'Ossetian; Ossetic']), 'iso_code' => 'os', 'is_active' => true],
            ['name' => json_encode(['en' => 'Pali']), 'iso_code' => 'pi', 'is_active' => true],
            ['name' => json_encode(['en' => 'Panjabi']), 'iso_code' => 'pa', 'is_active' => true],
            ['name' => json_encode(['en' => 'Persian']), 'iso_code' => 'fa', 'is_active' => true],
            ['name' => json_encode(['en' => 'Polish']), 'iso_code' => 'pl', 'is_active' => true],
            ['name' => json_encode(['en' => 'Portuguese']), 'iso_code' => 'pt', 'is_active' => true],
            ['name' => json_encode(['en' => 'Pushto']), 'iso_code' => 'ps', 'is_active' => true],
            ['name' => json_encode(['en' => 'Quechua']), 'iso_code' => 'qu', 'is_active' => true],
            ['name' => json_encode(['en' => 'Raeto-Romance']), 'iso_code' => 'rm', 'is_active' => true],
            ['name' => json_encode(['en' => 'Romanian']), 'iso_code' => 'ro', 'is_active' => true],
            ['name' => json_encode(['en' => 'Rundi']), 'iso_code' => 'rn', 'is_active' => true],
            ['name' => json_encode(['en' => 'Russian']), 'iso_code' => 'ru', 'is_active' => true],
            ['name' => json_encode(['en' => 'Samoan']), 'iso_code' => 'sm', 'is_active' => true],
            ['name' => json_encode(['en' => 'Sango']), 'iso_code' => 'sg', 'is_active' => true],
            ['name' => json_encode(['en' => 'Sanskrit']), 'iso_code' => 'sa', 'is_active' => true],
            ['name' => json_encode(['en' => 'Sardinian']), 'iso_code' => 'sc', 'is_active' => true],
            ['name' => json_encode(['en' => 'Serbian']), 'iso_code' => 'sr', 'is_active' => true],
            ['name' => json_encode(['en' => 'Shona']), 'iso_code' => 'sn', 'is_active' => true],
            ['name' => json_encode(['en' => 'Sichuan Yi']), 'iso_code' => 'ii', 'is_active' => true],
            ['name' => json_encode(['en' => 'Sindhi']), 'iso_code' => 'sd', 'is_active' => true],
            ['name' => json_encode(['en' => 'Sinhala; Sinhalese']), 'iso_code' => 'si', 'is_active' => true],
            ['name' => json_encode(['en' => 'Slovak']), 'iso_code' => 'sk', 'is_active' => true],
            ['name' => json_encode(['en' => 'Slovenian']), 'iso_code' => 'sl', 'is_active' => true],
            ['name' => json_encode(['en' => 'Somali']), 'iso_code' => 'so', 'is_active' => true],
            ['name' => json_encode(['en' => 'Sotho, Southern']), 'iso_code' => 'st', 'is_active' => true],
            ['name' => json_encode(['en' => 'Spanish; Castilian']), 'iso_code' => 'es', 'is_active' => true],
            ['name' => json_encode(['en' => 'Sundanese']), 'iso_code' => 'su', 'is_active' => true],
            ['name' => json_encode(['en' => 'Swahili']), 'iso_code' => 'sw', 'is_active' => true],
            ['name' => json_encode(['en' => 'Swati']), 'iso_code' => 'ss', 'is_active' => true],
            ['name' => json_encode(['en' => 'Swedish']), 'iso_code' => 'sv', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tagalog']), 'iso_code' => 'tl', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tahitian']), 'iso_code' => 'ty', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tajik']), 'iso_code' => 'tg', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tamil']), 'iso_code' => 'ta', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tatar']), 'iso_code' => 'tt', 'is_active' => true],
            ['name' => json_encode(['en' => 'Telugu']), 'iso_code' => 'te', 'is_active' => true],
            ['name' => json_encode(['en' => 'Thai']), 'iso_code' => 'th', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tibetan']), 'iso_code' => 'bo', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tigrinya']), 'iso_code' => 'ti', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tonga (Tonga Islands)']), 'iso_code' => 'to', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tsonga']), 'iso_code' => 'ts', 'is_active' => true],
            ['name' => json_encode(['en' => 'Tswana']), 'iso_code' => 'tn', 'is_active' => true],
            ['name' => json_encode(['en' => 'Turkish']), 'iso_code' => 'tr', 'is_active' => true],
            ['name' => json_encode(['en' => 'Turkmen']), 'iso_code' => 'tk', 'is_active' => true],
            ['name' => json_encode(['en' => 'Twi']), 'iso_code' => 'tw', 'is_active' => true],
            ['name' => json_encode(['en' => 'Uighur']), 'iso_code' => 'ug', 'is_active' => true],
            ['name' => json_encode(['en' => 'Ukrainian']), 'iso_code' => 'uk', 'is_active' => true],
            ['name' => json_encode(['en' => 'Urdu']), 'iso_code' => 'ur', 'is_active' => true],
            ['name' => json_encode(['en' => 'Uzbek']), 'iso_code' => 'uz', 'is_active' => true],
            ['name' => json_encode(['en' => 'Venda']), 'iso_code' => 've', 'is_active' => true],
            ['name' => json_encode(['en' => 'Vietnamese']), 'iso_code' => 'vi', 'is_active' => true],
            ['name' => json_encode(['en' => 'Volapuk']), 'iso_code' => 'vo', 'is_active' => true],
            ['name' => json_encode(['en' => 'Walloon']), 'iso_code' => 'wa', 'is_active' => true],
            ['name' => json_encode(['en' => 'Welsh']), 'iso_code' => 'cy', 'is_active' => true],
            ['name' => json_encode(['en' => 'Wolof']), 'iso_code' => 'wo', 'is_active' => true],
            ['name' => json_encode(['en' => 'Xhosa']), 'iso_code' => 'xh', 'is_active' => true],
            ['name' => json_encode(['en' => 'Yiddish']), 'iso_code' => 'yi', 'is_active' => true],
            ['name' => json_encode(['en' => 'Yoruba']), 'iso_code' => 'yo', 'is_active' => true],
            ['name' => json_encode(['en' => 'Zhuang; Chuang']), 'iso_code' => 'za', 'is_active' => true],
            ['name' => json_encode(['en' => 'Zulu']), 'iso_code' => 'zu', 'is_active' => true],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('languages');
    }
};
