<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('languages', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('iso_code')->index();
        });

        \DB::table('languages')->insert([
            ['id' => 1, 'name' => 'Abkhazian', 'iso_code' => 'ab'],
            ['id' => 2, 'name' => 'Afar', 'iso_code' => 'aa'],
            ['id' => 3, 'name' => 'Afrikaans', 'iso_code' => 'af'],
            ['id' => 4, 'name' => 'Albanian', 'iso_code' => 'sq'],
            ['id' => 5, 'name' => 'Amharic', 'iso_code' => 'am'],
            ['id' => 6, 'name' => 'Arabic', 'iso_code' => 'ar'],
            ['id' => 7, 'name' => 'Aragonese', 'iso_code' => 'an'],
            ['id' => 8, 'name' => 'Armenian', 'iso_code' => 'hy'],
            ['id' => 9, 'name' => 'Assamese', 'iso_code' => 'as'],
            ['id' => 10, 'name' => 'Avestan', 'iso_code' => 'ae'],
            ['id' => 11, 'name' => 'Aymara', 'iso_code' => 'ay'],
            ['id' => 12, 'name' => 'Azerbaijani', 'iso_code' => 'az'],
            ['id' => 13, 'name' => 'Bashkir', 'iso_code' => 'ba'],
            ['id' => 14, 'name' => 'Basque', 'iso_code' => 'eu'],
            ['id' => 15, 'name' => 'Belarusian', 'iso_code' => 'be'],
            ['id' => 16, 'name' => 'Bengali', 'iso_code' => 'bn'],
            ['id' => 17, 'name' => 'Bihari', 'iso_code' => 'bh'],
            ['id' => 18, 'name' => 'Bislama', 'iso_code' => 'bi'],
            ['id' => 19, 'name' => 'Bosnian', 'iso_code' => 'bs'],
            ['id' => 20, 'name' => 'Breton', 'iso_code' => 'br'],
            ['id' => 21, 'name' => 'Bulgarian', 'iso_code' => 'bg'],
            ['id' => 22, 'name' => 'Burmese', 'iso_code' => 'my'],
            ['id' => 23, 'name' => 'Catalan', 'iso_code' => 'ca'],
            ['id' => 24, 'name' => 'Chamorro', 'iso_code' => 'ch'],
            ['id' => 25, 'name' => 'Chechen', 'iso_code' => 'ce'],
            ['id' => 26, 'name' => 'Chinese', 'iso_code' => 'zh'],
            ['id' => 27, 'name' => 'Church Slavic; Slavonic; Old Bulgarian', 'iso_code' => 'cu'],
            ['id' => 28, 'name' => 'Chuvash', 'iso_code' => 'cv'],
            ['id' => 29, 'name' => 'Cornish', 'iso_code' => 'kw'],
            ['id' => 30, 'name' => 'Corsican', 'iso_code' => 'co'],
            ['id' => 31, 'name' => 'Croatian', 'iso_code' => 'hr'],
            ['id' => 32, 'name' => 'Czech', 'iso_code' => 'cs'],
            ['id' => 33, 'name' => 'Danish', 'iso_code' => 'da'],
            ['id' => 34, 'name' => 'Divehi; Dhivehi; Maldivian', 'iso_code' => 'dv'],
            ['id' => 35, 'name' => 'Dutch', 'iso_code' => 'nl'],
            ['id' => 36, 'name' => 'Dzongkha', 'iso_code' => 'dz'],
            ['id' => 37, 'name' => 'English', 'iso_code' => 'en'],
            ['id' => 38, 'name' => 'Esperanto', 'iso_code' => 'eo'],
            ['id' => 39, 'name' => 'Estonian', 'iso_code' => 'et'],
            ['id' => 40, 'name' => 'Faroese', 'iso_code' => 'fo'],
            ['id' => 41, 'name' => 'Fijian', 'iso_code' => 'fj'],
            ['id' => 42, 'name' => 'Finnish', 'iso_code' => 'fi'],
            ['id' => 43, 'name' => 'French', 'iso_code' => 'fr'],
            ['id' => 44, 'name' => 'Gaelic; Scottish Gaelic', 'iso_code' => 'gd'],
            ['id' => 45, 'name' => 'Galician', 'iso_code' => 'gl'],
            ['id' => 46, 'name' => 'Georgian', 'iso_code' => 'ka'],
            ['id' => 47, 'name' => 'German', 'iso_code' => 'de'],
            ['id' => 48, 'name' => 'Greek, Modern (1453-)', 'iso_code' => 'el'],
            ['id' => 49, 'name' => 'Guarani', 'iso_code' => 'gn'],
            ['id' => 50, 'name' => 'Gujarati', 'iso_code' => 'gu'],
            ['id' => 51, 'name' => 'Haitian; Haitian Creole', 'iso_code' => 'ht'],
            ['id' => 52, 'name' => 'Hausa', 'iso_code' => 'ha'],
            ['id' => 53, 'name' => 'Hebrew', 'iso_code' => 'he'],
            ['id' => 54, 'name' => 'Herero', 'iso_code' => 'hz'],
            ['id' => 55, 'name' => 'Hindi', 'iso_code' => 'hi'],
            ['id' => 56, 'name' => 'Hiri Motu', 'iso_code' => 'ho'],
            ['id' => 57, 'name' => 'Hungarian', 'iso_code' => 'hu'],
            ['id' => 58, 'name' => 'Icelandic', 'iso_code' => 'is'],
            ['id' => 59, 'name' => 'Ido', 'iso_code' => 'io'],
            ['id' => 60, 'name' => 'Indonesian', 'iso_code' => 'id'],
            ['id' => 61, 'name' => 'Interlingue', 'iso_code' => 'ie'],
            ['id' => 62, 'name' => 'Inuktitut', 'iso_code' => 'iu'],
            ['id' => 63, 'name' => 'Inupiaq', 'iso_code' => 'ik'],
            ['id' => 64, 'name' => 'Irish', 'iso_code' => 'ga'],
            ['id' => 65, 'name' => 'Italian', 'iso_code' => 'it'],
            ['id' => 66, 'name' => 'Japanese', 'iso_code' => 'ja'],
            ['id' => 67, 'name' => 'Javanese', 'iso_code' => 'jv'],
            ['id' => 68, 'name' => 'Kalaallisut', 'iso_code' => 'kl'],
            ['id' => 69, 'name' => 'Kannada', 'iso_code' => 'kn'],
            ['id' => 70, 'name' => 'Kashmiri', 'iso_code' => 'ks'],
            ['id' => 71, 'name' => 'Kazakh', 'iso_code' => 'kk'],
            ['id' => 72, 'name' => 'Khmer', 'iso_code' => 'km'],
            ['id' => 73, 'name' => 'Kikuyu; Gikuyu', 'iso_code' => 'ki'],
            ['id' => 74, 'name' => 'Kinyarwanda', 'iso_code' => 'rw'],
            ['id' => 75, 'name' => 'Kirghiz', 'iso_code' => 'ky'],
            ['id' => 76, 'name' => 'Komi', 'iso_code' => 'kv'],
            ['id' => 77, 'name' => 'Korean', 'iso_code' => 'ko'],
            ['id' => 78, 'name' => 'Kuanyama; Kwanyama', 'iso_code' => 'kj'],
            ['id' => 79, 'name' => 'Kurdish', 'iso_code' => 'ku'],
            ['id' => 80, 'name' => 'Lao', 'iso_code' => 'lo'],
            ['id' => 81, 'name' => 'Latin', 'iso_code' => 'la'],
            ['id' => 82, 'name' => 'Latvian', 'iso_code' => 'lv'],
            ['id' => 83, 'name' => 'Limburgan; Limburger; Limburgish', 'iso_code' => 'li'],
            ['id' => 84, 'name' => 'Lingala', 'iso_code' => 'ln'],
            ['id' => 85, 'name' => 'Lithuanian', 'iso_code' => 'lt'],
            ['id' => 86, 'name' => 'Luxembourgish; Letzeburgesch', 'iso_code' => 'lb'],
            ['id' => 87, 'name' => 'Macedonian', 'iso_code' => 'mk'],
            ['id' => 88, 'name' => 'Malagasy', 'iso_code' => 'mg'],
            ['id' => 89, 'name' => 'Malay', 'iso_code' => 'ms'],
            ['id' => 90, 'name' => 'Malayalam', 'iso_code' => 'ml'],
            ['id' => 91, 'name' => 'Maltese', 'iso_code' => 'mt'],
            ['id' => 92, 'name' => 'Manx', 'iso_code' => 'gv'],
            ['id' => 93, 'name' => 'Maori', 'iso_code' => 'mi'],
            ['id' => 94, 'name' => 'Marathi', 'iso_code' => 'mr'],
            ['id' => 95, 'name' => 'Marshallese', 'iso_code' => 'mh'],
            ['id' => 96, 'name' => 'Moldavian', 'iso_code' => 'mo'],
            ['id' => 97, 'name' => 'Mongolian', 'iso_code' => 'mn'],
            ['id' => 98, 'name' => 'Nauru', 'iso_code' => 'na'],
            ['id' => 99, 'name' => 'Navaho, Navajo', 'iso_code' => 'nv'],
            ['id' => 100, 'name' => 'Ndebele, North', 'iso_code' => 'nd'],
            ['id' => 101, 'name' => 'Ndebele, South', 'iso_code' => 'nr'],
            ['id' => 102, 'name' => 'Ndonga', 'iso_code' => 'ng'],
            ['id' => 103, 'name' => 'Nepali', 'iso_code' => 'ne'],
            ['id' => 104, 'name' => 'Northern Sami', 'iso_code' => 'se'],
            ['id' => 105, 'name' => 'Norwegian', 'iso_code' => 'no'],
            ['id' => 106, 'name' => 'Norwegian Bokmal', 'iso_code' => 'nb'],
            ['id' => 107, 'name' => 'Norwegian Nynorsk', 'iso_code' => 'nn'],
            ['id' => 108, 'name' => 'Nyanja; Chichewa; Chewa', 'iso_code' => 'ny'],
            ['id' => 109, 'name' => 'Occitan (post 1500); Provencal', 'iso_code' => 'oc'],
            ['id' => 110, 'name' => 'Oriya', 'iso_code' => 'or'],
            ['id' => 111, 'name' => 'Oromo', 'iso_code' => 'om'],
            ['id' => 112, 'name' => 'Ossetian; Ossetic', 'iso_code' => 'os'],
            ['id' => 113, 'name' => 'Pali', 'iso_code' => 'pi'],
            ['id' => 114, 'name' => 'Panjabi', 'iso_code' => 'pa'],
            ['id' => 115, 'name' => 'Persian', 'iso_code' => 'fa'],
            ['id' => 116, 'name' => 'Polish', 'iso_code' => 'pl'],
            ['id' => 117, 'name' => 'Portuguese', 'iso_code' => 'pt'],
            ['id' => 118, 'name' => 'Pushto', 'iso_code' => 'ps'],
            ['id' => 119, 'name' => 'Quechua', 'iso_code' => 'qu'],
            ['id' => 120, 'name' => 'Raeto-Romance', 'iso_code' => 'rm'],
            ['id' => 121, 'name' => 'Romanian', 'iso_code' => 'ro'],
            ['id' => 122, 'name' => 'Rundi', 'iso_code' => 'rn'],
            ['id' => 123, 'name' => 'Russian', 'iso_code' => 'ru'],
            ['id' => 124, 'name' => 'Samoan', 'iso_code' => 'sm'],
            ['id' => 125, 'name' => 'Sango', 'iso_code' => 'sg'],
            ['id' => 126, 'name' => 'Sanskrit', 'iso_code' => 'sa'],
            ['id' => 127, 'name' => 'Sardinian', 'iso_code' => 'sc'],
            ['id' => 128, 'name' => 'Serbian', 'iso_code' => 'sr'],
            ['id' => 129, 'name' => 'Shona', 'iso_code' => 'sn'],
            ['id' => 130, 'name' => 'Sichuan Yi', 'iso_code' => 'ii'],
            ['id' => 131, 'name' => 'Sindhi', 'iso_code' => 'sd'],
            ['id' => 132, 'name' => 'Sinhala; Sinhalese', 'iso_code' => 'si'],
            ['id' => 133, 'name' => 'Slovak', 'iso_code' => 'sk'],
            ['id' => 134, 'name' => 'Slovenian', 'iso_code' => 'sl'],
            ['id' => 135, 'name' => 'Somali', 'iso_code' => 'so'],
            ['id' => 136, 'name' => 'Sotho, Southern', 'iso_code' => 'st'],
            ['id' => 137, 'name' => 'Spanish; Castilian', 'iso_code' => 'es'],
            ['id' => 138, 'name' => 'Sundanese', 'iso_code' => 'su'],
            ['id' => 139, 'name' => 'Swahili', 'iso_code' => 'sw'],
            ['id' => 140, 'name' => 'Swati', 'iso_code' => 'ss'],
            ['id' => 141, 'name' => 'Swedish', 'iso_code' => 'sv'],
            ['id' => 142, 'name' => 'Tagalog', 'iso_code' => 'tl'],
            ['id' => 143, 'name' => 'Tahitian', 'iso_code' => 'ty'],
            ['id' => 144, 'name' => 'Tajik', 'iso_code' => 'tg'],
            ['id' => 145, 'name' => 'Tamil', 'iso_code' => 'ta'],
            ['id' => 146, 'name' => 'Tatar', 'iso_code' => 'tt'],
            ['id' => 147, 'name' => 'Telugu', 'iso_code' => 'te'],
            ['id' => 148, 'name' => 'Thai', 'iso_code' => 'th'],
            ['id' => 149, 'name' => 'Tibetan', 'iso_code' => 'bo'],
            ['id' => 150, 'name' => 'Tigrinya', 'iso_code' => 'ti'],
            ['id' => 151, 'name' => 'Tonga (Tonga Islands)', 'iso_code' => 'to'],
            ['id' => 152, 'name' => 'Tsonga', 'iso_code' => 'ts'],
            ['id' => 153, 'name' => 'Tswana', 'iso_code' => 'tn'],
            ['id' => 154, 'name' => 'Turkish', 'iso_code' => 'tr'],
            ['id' => 155, 'name' => 'Turkmen', 'iso_code' => 'tk'],
            ['id' => 156, 'name' => 'Twi', 'iso_code' => 'tw'],
            ['id' => 157, 'name' => 'Uighur', 'iso_code' => 'ug'],
            ['id' => 158, 'name' => 'Ukrainian', 'iso_code' => 'uk'],
            ['id' => 159, 'name' => 'Urdu', 'iso_code' => 'ur'],
            ['id' => 160, 'name' => 'Uzbek', 'iso_code' => 'uz'],
            ['id' => 161, 'name' => 'Venda', 'iso_code' => 've'],
            ['id' => 162, 'name' => 'Vietnamese', 'iso_code' => 'vi'],
            ['id' => 163, 'name' => 'Volapuk', 'iso_code' => 'vo'],
            ['id' => 164, 'name' => 'Walloon', 'iso_code' => 'wa'],
            ['id' => 165, 'name' => 'Welsh', 'iso_code' => 'cy'],
            ['id' => 166, 'name' => 'Wolof', 'iso_code' => 'wo'],
            ['id' => 167, 'name' => 'Xhosa', 'iso_code' => 'xh'],
            ['id' => 168, 'name' => 'Yiddish', 'iso_code' => 'yi'],
            ['id' => 169, 'name' => 'Yoruba', 'iso_code' => 'yo'],
            ['id' => 170, 'name' => 'Zhuang; Chuang', 'iso_code' => 'za'],
            ['id' => 171, 'name' => 'Zulu', 'iso_code' => 'zu'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('languages');
    }
};
