<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('languages', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('iso_code')->index();
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });

        \DB::table('languages')->insert([
            ['id' => 1, 'name' => 'Abkhazian', 'iso_code' => 'ab', 'is_active' => true],
            ['id' => 2, 'name' => 'Afar', 'iso_code' => 'aa', 'is_active' => true],
            ['id' => 3, 'name' => 'Afrikaans', 'iso_code' => 'af', 'is_active' => true],
            ['id' => 4, 'name' => 'Albanian', 'iso_code' => 'sq', 'is_active' => true],
            ['id' => 5, 'name' => 'Amharic', 'iso_code' => 'am', 'is_active' => true],
            ['id' => 6, 'name' => 'Arabic', 'iso_code' => 'ar', 'is_active' => true],
            ['id' => 7, 'name' => 'Aragonese', 'iso_code' => 'an', 'is_active' => true],
            ['id' => 8, 'name' => 'Armenian', 'iso_code' => 'hy', 'is_active' => true],
            ['id' => 9, 'name' => 'Assamese', 'iso_code' => 'as', 'is_active' => true],
            ['id' => 10, 'name' => 'Avestan', 'iso_code' => 'ae', 'is_active' => true],
            ['id' => 11, 'name' => 'Aymara', 'iso_code' => 'ay', 'is_active' => true],
            ['id' => 12, 'name' => 'Azerbaijani', 'iso_code' => 'az', 'is_active' => true],
            ['id' => 13, 'name' => 'Bashkir', 'iso_code' => 'ba', 'is_active' => true],
            ['id' => 14, 'name' => 'Basque', 'iso_code' => 'eu', 'is_active' => true],
            ['id' => 15, 'name' => 'Belarusian', 'iso_code' => 'be', 'is_active' => true],
            ['id' => 16, 'name' => 'Bengali', 'iso_code' => 'bn', 'is_active' => true],
            ['id' => 17, 'name' => 'Bihari', 'iso_code' => 'bh', 'is_active' => true],
            ['id' => 18, 'name' => 'Bislama', 'iso_code' => 'bi', 'is_active' => true],
            ['id' => 19, 'name' => 'Bosnian', 'iso_code' => 'bs', 'is_active' => true],
            ['id' => 20, 'name' => 'Breton', 'iso_code' => 'br', 'is_active' => true],
            ['id' => 21, 'name' => 'Bulgarian', 'iso_code' => 'bg', 'is_active' => true],
            ['id' => 22, 'name' => 'Burmese', 'iso_code' => 'my', 'is_active' => true],
            ['id' => 23, 'name' => 'Catalan', 'iso_code' => 'ca', 'is_active' => true],
            ['id' => 24, 'name' => 'Chamorro', 'iso_code' => 'ch', 'is_active' => true],
            ['id' => 25, 'name' => 'Chechen', 'iso_code' => 'ce', 'is_active' => true],
            ['id' => 26, 'name' => 'Chinese', 'iso_code' => 'zh', 'is_active' => true],
            ['id' => 27, 'name' => 'Church Slavic; Slavonic; Old Bulgarian', 'iso_code' => 'cu', 'is_active' => true],
            ['id' => 28, 'name' => 'Chuvash', 'iso_code' => 'cv', 'is_active' => true],
            ['id' => 29, 'name' => 'Cornish', 'iso_code' => 'kw', 'is_active' => true],
            ['id' => 30, 'name' => 'Corsican', 'iso_code' => 'co', 'is_active' => true],
            ['id' => 31, 'name' => 'Croatian', 'iso_code' => 'hr', 'is_active' => true],
            ['id' => 32, 'name' => 'Czech', 'iso_code' => 'cs', 'is_active' => true],
            ['id' => 33, 'name' => 'Danish', 'iso_code' => 'da', 'is_active' => true],
            ['id' => 34, 'name' => 'Divehi; Dhivehi; Maldivian', 'iso_code' => 'dv', 'is_active' => true],
            ['id' => 35, 'name' => 'Dutch', 'iso_code' => 'nl', 'is_active' => true],
            ['id' => 36, 'name' => 'Dzongkha', 'iso_code' => 'dz', 'is_active' => true],
            ['id' => 37, 'name' => 'English', 'iso_code' => 'en', 'is_active' => true],
            ['id' => 38, 'name' => 'Esperanto', 'iso_code' => 'eo', 'is_active' => true],
            ['id' => 39, 'name' => 'Estonian', 'iso_code' => 'et', 'is_active' => true],
            ['id' => 40, 'name' => 'Faroese', 'iso_code' => 'fo', 'is_active' => true],
            ['id' => 41, 'name' => 'Fijian', 'iso_code' => 'fj', 'is_active' => true],
            ['id' => 42, 'name' => 'Finnish', 'iso_code' => 'fi', 'is_active' => true],
            ['id' => 43, 'name' => 'French', 'iso_code' => 'fr', 'is_active' => true],
            ['id' => 44, 'name' => 'Gaelic; Scottish Gaelic', 'iso_code' => 'gd', 'is_active' => true],
            ['id' => 45, 'name' => 'Galician', 'iso_code' => 'gl', 'is_active' => true],
            ['id' => 46, 'name' => 'Georgian', 'iso_code' => 'ka', 'is_active' => true],
            ['id' => 47, 'name' => 'German', 'iso_code' => 'de', 'is_active' => true],
            ['id' => 48, 'name' => 'Greek, Modern (1453-)', 'iso_code' => 'el', 'is_active' => true],
            ['id' => 49, 'name' => 'Guarani', 'iso_code' => 'gn', 'is_active' => true],
            ['id' => 50, 'name' => 'Gujarati', 'iso_code' => 'gu', 'is_active' => true],
            ['id' => 51, 'name' => 'Haitian; Haitian Creole', 'iso_code' => 'ht', 'is_active' => true],
            ['id' => 52, 'name' => 'Hausa', 'iso_code' => 'ha', 'is_active' => true],
            ['id' => 53, 'name' => 'Hebrew', 'iso_code' => 'he', 'is_active' => true],
            ['id' => 54, 'name' => 'Herero', 'iso_code' => 'hz', 'is_active' => true],
            ['id' => 55, 'name' => 'Hindi', 'iso_code' => 'hi', 'is_active' => true],
            ['id' => 56, 'name' => 'Hiri Motu', 'iso_code' => 'ho', 'is_active' => true],
            ['id' => 57, 'name' => 'Hungarian', 'iso_code' => 'hu', 'is_active' => true],
            ['id' => 58, 'name' => 'Icelandic', 'iso_code' => 'is', 'is_active' => true],
            ['id' => 59, 'name' => 'Ido', 'iso_code' => 'io', 'is_active' => true],
            ['id' => 60, 'name' => 'Indonesian', 'iso_code' => 'id', 'is_active' => true],
            ['id' => 61, 'name' => 'Interlingue', 'iso_code' => 'ie', 'is_active' => true],
            ['id' => 62, 'name' => 'Inuktitut', 'iso_code' => 'iu', 'is_active' => true],
            ['id' => 63, 'name' => 'Inupiaq', 'iso_code' => 'ik', 'is_active' => true],
            ['id' => 64, 'name' => 'Irish', 'iso_code' => 'ga', 'is_active' => true],
            ['id' => 65, 'name' => 'Italian', 'iso_code' => 'it', 'is_active' => true],
            ['id' => 66, 'name' => 'Japanese', 'iso_code' => 'ja', 'is_active' => true],
            ['id' => 67, 'name' => 'Javanese', 'iso_code' => 'jv', 'is_active' => true],
            ['id' => 68, 'name' => 'Kalaallisut', 'iso_code' => 'kl', 'is_active' => true],
            ['id' => 69, 'name' => 'Kannada', 'iso_code' => 'kn', 'is_active' => true],
            ['id' => 70, 'name' => 'Kashmiri', 'iso_code' => 'ks', 'is_active' => true],
            ['id' => 71, 'name' => 'Kazakh', 'iso_code' => 'kk', 'is_active' => true],
            ['id' => 72, 'name' => 'Khmer', 'iso_code' => 'km', 'is_active' => true],
            ['id' => 73, 'name' => 'Kikuyu; Gikuyu', 'iso_code' => 'ki', 'is_active' => true],
            ['id' => 74, 'name' => 'Kinyarwanda', 'iso_code' => 'rw', 'is_active' => true],
            ['id' => 75, 'name' => 'Kirghiz', 'iso_code' => 'ky', 'is_active' => true],
            ['id' => 76, 'name' => 'Komi', 'iso_code' => 'kv', 'is_active' => true],
            ['id' => 77, 'name' => 'Korean', 'iso_code' => 'ko', 'is_active' => true],
            ['id' => 78, 'name' => 'Kuanyama; Kwanyama', 'iso_code' => 'kj', 'is_active' => true],
            ['id' => 79, 'name' => 'Kurdish', 'iso_code' => 'ku', 'is_active' => true],
            ['id' => 80, 'name' => 'Lao', 'iso_code' => 'lo', 'is_active' => true],
            ['id' => 81, 'name' => 'Latin', 'iso_code' => 'la', 'is_active' => true],
            ['id' => 82, 'name' => 'Latvian', 'iso_code' => 'lv', 'is_active' => true],
            ['id' => 83, 'name' => 'Limburgan; Limburger; Limburgish', 'iso_code' => 'li', 'is_active' => true],
            ['id' => 84, 'name' => 'Lingala', 'iso_code' => 'ln', 'is_active' => true],
            ['id' => 85, 'name' => 'Lithuanian', 'iso_code' => 'lt', 'is_active' => true],
            ['id' => 86, 'name' => 'Luxembourgish; Letzeburgesch', 'iso_code' => 'lb', 'is_active' => true],
            ['id' => 87, 'name' => 'Macedonian', 'iso_code' => 'mk', 'is_active' => true],
            ['id' => 88, 'name' => 'Malagasy', 'iso_code' => 'mg', 'is_active' => true],
            ['id' => 89, 'name' => 'Malay', 'iso_code' => 'ms', 'is_active' => true],
            ['id' => 90, 'name' => 'Malayalam', 'iso_code' => 'ml', 'is_active' => true],
            ['id' => 91, 'name' => 'Maltese', 'iso_code' => 'mt', 'is_active' => true],
            ['id' => 92, 'name' => 'Manx', 'iso_code' => 'gv', 'is_active' => true],
            ['id' => 93, 'name' => 'Maori', 'iso_code' => 'mi', 'is_active' => true],
            ['id' => 94, 'name' => 'Marathi', 'iso_code' => 'mr', 'is_active' => true],
            ['id' => 95, 'name' => 'Marshallese', 'iso_code' => 'mh', 'is_active' => true],
            ['id' => 96, 'name' => 'Moldavian', 'iso_code' => 'mo', 'is_active' => true],
            ['id' => 97, 'name' => 'Mongolian', 'iso_code' => 'mn', 'is_active' => true],
            ['id' => 98, 'name' => 'Nauru', 'iso_code' => 'na', 'is_active' => true],
            ['id' => 99, 'name' => 'Navaho, Navajo', 'iso_code' => 'nv', 'is_active' => true],
            ['id' => 100, 'name' => 'Ndebele, North', 'iso_code' => 'nd', 'is_active' => true],
            ['id' => 101, 'name' => 'Ndebele, South', 'iso_code' => 'nr', 'is_active' => true],
            ['id' => 102, 'name' => 'Ndonga', 'iso_code' => 'ng', 'is_active' => true],
            ['id' => 103, 'name' => 'Nepali', 'iso_code' => 'ne', 'is_active' => true],
            ['id' => 104, 'name' => 'Northern Sami', 'iso_code' => 'se', 'is_active' => true],
            ['id' => 105, 'name' => 'Norwegian', 'iso_code' => 'no', 'is_active' => true],
            ['id' => 106, 'name' => 'Norwegian Bokmal', 'iso_code' => 'nb', 'is_active' => true],
            ['id' => 107, 'name' => 'Norwegian Nynorsk', 'iso_code' => 'nn', 'is_active' => true],
            ['id' => 108, 'name' => 'Nyanja; Chichewa; Chewa', 'iso_code' => 'ny', 'is_active' => true],
            ['id' => 109, 'name' => 'Occitan (post 1500); Provencal', 'iso_code' => 'oc', 'is_active' => true],
            ['id' => 110, 'name' => 'Oriya', 'iso_code' => 'or', 'is_active' => true],
            ['id' => 111, 'name' => 'Oromo', 'iso_code' => 'om', 'is_active' => true],
            ['id' => 112, 'name' => 'Ossetian; Ossetic', 'iso_code' => 'os', 'is_active' => true],
            ['id' => 113, 'name' => 'Pali', 'iso_code' => 'pi', 'is_active' => true],
            ['id' => 114, 'name' => 'Panjabi', 'iso_code' => 'pa', 'is_active' => true],
            ['id' => 115, 'name' => 'Persian', 'iso_code' => 'fa', 'is_active' => true],
            ['id' => 116, 'name' => 'Polish', 'iso_code' => 'pl', 'is_active' => true],
            ['id' => 117, 'name' => 'Portuguese', 'iso_code' => 'pt', 'is_active' => true],
            ['id' => 118, 'name' => 'Pushto', 'iso_code' => 'ps', 'is_active' => true],
            ['id' => 119, 'name' => 'Quechua', 'iso_code' => 'qu', 'is_active' => true],
            ['id' => 120, 'name' => 'Raeto-Romance', 'iso_code' => 'rm', 'is_active' => true],
            ['id' => 121, 'name' => 'Romanian', 'iso_code' => 'ro', 'is_active' => true],
            ['id' => 122, 'name' => 'Rundi', 'iso_code' => 'rn', 'is_active' => true],
            ['id' => 123, 'name' => 'Russian', 'iso_code' => 'ru', 'is_active' => true],
            ['id' => 124, 'name' => 'Samoan', 'iso_code' => 'sm', 'is_active' => true],
            ['id' => 125, 'name' => 'Sango', 'iso_code' => 'sg', 'is_active' => true],
            ['id' => 126, 'name' => 'Sanskrit', 'iso_code' => 'sa', 'is_active' => true],
            ['id' => 127, 'name' => 'Sardinian', 'iso_code' => 'sc', 'is_active' => true],
            ['id' => 128, 'name' => 'Serbian', 'iso_code' => 'sr', 'is_active' => true],
            ['id' => 129, 'name' => 'Shona', 'iso_code' => 'sn', 'is_active' => true],
            ['id' => 130, 'name' => 'Sichuan Yi', 'iso_code' => 'ii', 'is_active' => true],
            ['id' => 131, 'name' => 'Sindhi', 'iso_code' => 'sd', 'is_active' => true],
            ['id' => 132, 'name' => 'Sinhala; Sinhalese', 'iso_code' => 'si', 'is_active' => true],
            ['id' => 133, 'name' => 'Slovak', 'iso_code' => 'sk', 'is_active' => true],
            ['id' => 134, 'name' => 'Slovenian', 'iso_code' => 'sl', 'is_active' => true],
            ['id' => 135, 'name' => 'Somali', 'iso_code' => 'so', 'is_active' => true],
            ['id' => 136, 'name' => 'Sotho, Southern', 'iso_code' => 'st', 'is_active' => true],
            ['id' => 137, 'name' => 'Spanish; Castilian', 'iso_code' => 'es', 'is_active' => true],
            ['id' => 138, 'name' => 'Sundanese', 'iso_code' => 'su', 'is_active' => true],
            ['id' => 139, 'name' => 'Swahili', 'iso_code' => 'sw', 'is_active' => true],
            ['id' => 140, 'name' => 'Swati', 'iso_code' => 'ss', 'is_active' => true],
            ['id' => 141, 'name' => 'Swedish', 'iso_code' => 'sv', 'is_active' => true],
            ['id' => 142, 'name' => 'Tagalog', 'iso_code' => 'tl', 'is_active' => true],
            ['id' => 143, 'name' => 'Tahitian', 'iso_code' => 'ty', 'is_active' => true],
            ['id' => 144, 'name' => 'Tajik', 'iso_code' => 'tg', 'is_active' => true],
            ['id' => 145, 'name' => 'Tamil', 'iso_code' => 'ta', 'is_active' => true],
            ['id' => 146, 'name' => 'Tatar', 'iso_code' => 'tt', 'is_active' => true],
            ['id' => 147, 'name' => 'Telugu', 'iso_code' => 'te', 'is_active' => true],
            ['id' => 148, 'name' => 'Thai', 'iso_code' => 'th', 'is_active' => true],
            ['id' => 149, 'name' => 'Tibetan', 'iso_code' => 'bo', 'is_active' => true],
            ['id' => 150, 'name' => 'Tigrinya', 'iso_code' => 'ti', 'is_active' => true],
            ['id' => 151, 'name' => 'Tonga (Tonga Islands)', 'iso_code' => 'to', 'is_active' => true],
            ['id' => 152, 'name' => 'Tsonga', 'iso_code' => 'ts', 'is_active' => true],
            ['id' => 153, 'name' => 'Tswana', 'iso_code' => 'tn', 'is_active' => true],
            ['id' => 154, 'name' => 'Turkish', 'iso_code' => 'tr', 'is_active' => true],
            ['id' => 155, 'name' => 'Turkmen', 'iso_code' => 'tk', 'is_active' => true],
            ['id' => 156, 'name' => 'Twi', 'iso_code' => 'tw', 'is_active' => true],
            ['id' => 157, 'name' => 'Uighur', 'iso_code' => 'ug', 'is_active' => true],
            ['id' => 158, 'name' => 'Ukrainian', 'iso_code' => 'uk', 'is_active' => true],
            ['id' => 159, 'name' => 'Urdu', 'iso_code' => 'ur', 'is_active' => true],
            ['id' => 160, 'name' => 'Uzbek', 'iso_code' => 'uz', 'is_active' => true],
            ['id' => 161, 'name' => 'Venda', 'iso_code' => 've', 'is_active' => true],
            ['id' => 162, 'name' => 'Vietnamese', 'iso_code' => 'vi', 'is_active' => true],
            ['id' => 163, 'name' => 'Volapuk', 'iso_code' => 'vo', 'is_active' => true],
            ['id' => 164, 'name' => 'Walloon', 'iso_code' => 'wa', 'is_active' => true],
            ['id' => 165, 'name' => 'Welsh', 'iso_code' => 'cy', 'is_active' => true],
            ['id' => 166, 'name' => 'Wolof', 'iso_code' => 'wo', 'is_active' => true],
            ['id' => 167, 'name' => 'Xhosa', 'iso_code' => 'xh', 'is_active' => true],
            ['id' => 168, 'name' => 'Yiddish', 'iso_code' => 'yi', 'is_active' => true],
            ['id' => 169, 'name' => 'Yoruba', 'iso_code' => 'yo', 'is_active' => true],
            ['id' => 170, 'name' => 'Zhuang; Chuang', 'iso_code' => 'za', 'is_active' => true],
            ['id' => 171, 'name' => 'Zulu', 'iso_code' => 'zu', 'is_active' => true],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('languages');
    }
};
