<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('iso_code');
        });

        \DB::table('countries')->insert([
            array("name" => 'Afghanistan', "iso_code" => 'AF'),
            array("name" => 'Åland Islands', "iso_code" => 'AX'),
            array("name" => 'Albania', "iso_code" => 'AL'),
            array("name" => 'Algeria', "iso_code" => 'DZ'),
            array("name" => 'American Samoa', "iso_code" => 'AS'),
            array("name" => 'Andorra', "iso_code" => 'AD'),
            array("name" => 'Angola', "iso_code" => 'AO'),
            array("name" => 'Anguilla', "iso_code" => 'AI'),
            array("name" => 'Antarctica', "iso_code" => 'AQ'),
            array("name" => 'Antigua and Barbuda', "iso_code" => 'AG'),
            array("name" => 'Argentina', "iso_code" => 'AR'),
            array("name" => 'Armenia', "iso_code" => 'AM'),
            array("name" => 'Aruba', "iso_code" => 'AW'),
            array("name" => 'Australia', "iso_code" => 'AU'),
            array("name" => 'Austria', "iso_code" => 'AT'),
            array("name" => 'Azerbaijan', "iso_code" => 'AZ'),
            array("name" => 'Bahamas', "iso_code" => 'BS'),
            array("name" => 'Bahrain', "iso_code" => 'BH'),
            array("name" => 'Bangladesh', "iso_code" => 'BD'),
            array("name" => 'Barbados', "iso_code" => 'BB'),
            array("name" => 'Belarus', "iso_code" => 'BY'),
            array("name" => 'Belgium', "iso_code" => 'BE'),
            array("name" => 'Belize', "iso_code" => 'BZ'),
            array("name" => 'Benin', "iso_code" => 'BJ'),
            array("name" => 'Bermuda', "iso_code" => 'BM'),
            array("name" => 'Bhutan', "iso_code" => 'BT'),
            array("name" => 'Bolivia', "iso_code" => 'BO'),
            array("name" => 'Bosnia and Herzegovina', "iso_code" => 'BA'),
            array("name" => 'Botswana', "iso_code" => 'BW'),
            array("name" => 'Bouvet Island', "iso_code" => 'BV'),
            array("name" => 'Brazil', "iso_code" => 'BR'),
            array("name" => 'British Indian Ocean Territory', "iso_code" => 'IO'),
            array("name" => 'Brunei Darussalam', "iso_code" => 'BN'),
            array("name" => 'Bulgaria', "iso_code" => 'BG'),
            array("name" => 'Burkina Faso', "iso_code" => 'BF'),
            array("name" => 'Burundi', "iso_code" => 'BI'),
            array("name" => 'Cambodia', "iso_code" => 'KH'),
            array("name" => 'Cameroon', "iso_code" => 'CM'),
            array("name" => 'Canada', "iso_code" => 'CA'),
            array("name" => 'Cape Verde', "iso_code" => 'CV'),
            array("name" => 'Cayman Islands', "iso_code" => 'KY'),
            array("name" => 'Central African Republic', "iso_code" => 'CF'),
            array("name" => 'Chad', "iso_code" => 'TD'),
            array("name" => 'Chile', "iso_code" => 'CL'),
            array("name" => 'China', "iso_code" => 'CN'),
            array("name" => 'Christmas Island', "iso_code" => 'CX'),
            array("name" => 'Cocos (Keeling) Islands', "iso_code" => 'CC'),
            array("name" => 'Colombia', "iso_code" => 'CO'),
            array("name" => 'Comoros', "iso_code" => 'KM'),
            array("name" => 'Congo', "iso_code" => 'CG'),
            array("name" => 'Congo, The Democratic Republic of the', "iso_code" => 'CD'),
            array("name" => 'Cook Islands', "iso_code" => 'CK'),
            array("name" => 'Costa Rica', "iso_code" => 'CR'),
            array("name" => 'Cote D\'Ivoire', "iso_code" => 'CI'),
            array("name" => 'Croatia', "iso_code" => 'HR'),
            array("name" => 'Cuba', "iso_code" => 'CU'),
            array("name" => 'Cyprus', "iso_code" => 'CY'),
            array("name" => 'Czech Republic', "iso_code" => 'CZ'),
            array("name" => 'Denmark', "iso_code" => 'DK'),
            array("name" => 'Djibouti', "iso_code" => 'DJ'),
            array("name" => 'Dominica', "iso_code" => 'DM'),
            array("name" => 'Dominican Republic', "iso_code" => 'DO'),
            array("name" => 'Ecuador', "iso_code" => 'EC'),
            array("name" => 'Egypt', "iso_code" => 'EG'),
            array("name" => 'El Salvador', "iso_code" => 'SV'),
            array("name" => 'Equatorial Guinea', "iso_code" => 'GQ'),
            array("name" => 'Eritrea', "iso_code" => 'ER'),
            array("name" => 'Estonia', "iso_code" => 'EE'),
            array("name" => 'Ethiopia', "iso_code" => 'ET'),
            array("name" => 'Falkland Islands (Malvinas)', "iso_code" => 'FK'),
            array("name" => 'Faroe Islands', "iso_code" => 'FO'),
            array("name" => 'Fiji', "iso_code" => 'FJ'),
            array("name" => 'Finland', "iso_code" => 'FI'),
            array("name" => 'France', "iso_code" => 'FR'),
            array("name" => 'French Guiana', "iso_code" => 'GF'),
            array("name" => 'French Polynesia', "iso_code" => 'PF'),
            array("name" => 'French Southern Territories', "iso_code" => 'TF'),
            array("name" => 'Gabon', "iso_code" => 'GA'),
            array("name" => 'Gambia', "iso_code" => 'GM'),
            array("name" => 'Georgia', "iso_code" => 'GE'),
            array("name" => 'Germany', "iso_code" => 'DE'),
            array("name" => 'Ghana', "iso_code" => 'GH'),
            array("name" => 'Gibraltar', "iso_code" => 'GI'),
            array("name" => 'Greece', "iso_code" => 'GR'),
            array("name" => 'Greenland', "iso_code" => 'GL'),
            array("name" => 'Grenada', "iso_code" => 'GD'),
            array("name" => 'Guadeloupe', "iso_code" => 'GP'),
            array("name" => 'Guam', "iso_code" => 'GU'),
            array("name" => 'Guatemala', "iso_code" => 'GT'),
            array("name" => 'Guernsey', "iso_code" => 'GG'),
            array("name" => 'Guinea', "iso_code" => 'GN'),
            array("name" => 'Guinea-Bissau', "iso_code" => 'GW'),
            array("name" => 'Guyana', "iso_code" => 'GY'),
            array("name" => 'Haiti', "iso_code" => 'HT'),
            array("name" => 'Heard Island and Mcdonald Islands', "iso_code" => 'HM'),
            array("name" => 'Holy See (Vatican City State)', "iso_code" => 'VA'),
            array("name" => 'Honduras', "iso_code" => 'HN'),
            array("name" => 'Hong Kong', "iso_code" => 'HK'),
            array("name" => 'Hungary', "iso_code" => 'HU'),
            array("name" => 'Iceland', "iso_code" => 'IS'),
            array("name" => 'India', "iso_code" => 'IN'),
            array("name" => 'Indonesia', "iso_code" => 'ID'),
            array("name" => 'Iran, Islamic Republic Of', "iso_code" => 'IR'),
            array("name" => 'Iraq', "iso_code" => 'IQ'),
            array("name" => 'Ireland', "iso_code" => 'IE'),
            array("name" => 'Isle of Man', "iso_code" => 'IM'),
            array("name" => 'Israel', "iso_code" => 'IL'),
            array("name" => 'Italy', "iso_code" => 'IT'),
            array("name" => 'Jamaica', "iso_code" => 'JM'),
            array("name" => 'Japan', "iso_code" => 'JP'),
            array("name" => 'Jersey', "iso_code" => 'JE'),
            array("name" => 'Jordan', "iso_code" => 'JO'),
            array("name" => 'Kazakhstan', "iso_code" => 'KZ'),
            array("name" => 'Kenya', "iso_code" => 'KE'),
            array("name" => 'Kiribati', "iso_code" => 'KI'),
            array("name" => 'Korea, Democratic People\'S Republic of', "iso_code" => 'KP'),
            array("name" => 'Korea, Republic of', "iso_code" => 'KR'),
            array("name" => 'Kuwait', "iso_code" => 'KW'),
            array("name" => 'Kyrgyzstan', "iso_code" => 'KG'),
            array("name" => 'Laos', "iso_code" => 'LA'),
            array("name" => 'Latvia', "iso_code" => 'LV'),
            array("name" => 'Lebanon', "iso_code" => 'LB'),
            array("name" => 'Lesotho', "iso_code" => 'LS'),
            array("name" => 'Liberia', "iso_code" => 'LR'),
            array("name" => 'Libya', "iso_code" => 'LY'),
            array("name" => 'Liechtenstein', "iso_code" => 'LI'),
            array("name" => 'Lithuania', "iso_code" => 'LT'),
            array("name" => 'Luxembourg', "iso_code" => 'LU'),
            array("name" => 'Macao', "iso_code" => 'MO'),
            array("name" => 'North Macedonia', "iso_code" => 'MK'),
            array("name" => 'Madagascar', "iso_code" => 'MG'),
            array("name" => 'Malawi', "iso_code" => 'MW'),
            array("name" => 'Malaysia', "iso_code" => 'MY'),
            array("name" => 'Maldives', "iso_code" => 'MV'),
            array("name" => 'Mali', "iso_code" => 'ML'),
            array("name" => 'Malta', "iso_code" => 'MT'),
            array("name" => 'Marshall Islands', "iso_code" => 'MH'),
            array("name" => 'Martinique', "iso_code" => 'MQ'),
            array("name" => 'Mauritania', "iso_code" => 'MR'),
            array("name" => 'Mauritius', "iso_code" => 'MU'),
            array("name" => 'Mayotte', "iso_code" => 'YT'),
            array("name" => 'Mexico', "iso_code" => 'MX'),
            array("name" => 'Micronesia, Federated States of', "iso_code" => 'FM'),
            array("name" => 'Moldova, Republic of', "iso_code" => 'MD'),
            array("name" => 'Monaco', "iso_code" => 'MC'),
            array("name" => 'Mongolia', "iso_code" => 'MN'),
            array("name" => 'Montserrat', "iso_code" => 'MS'),
            array("name" => 'Morocco', "iso_code" => 'MA'),
            array("name" => 'Mozambique', "iso_code" => 'MZ'),
            array("name" => 'Myanmar', "iso_code" => 'MM'),
            array("name" => 'Namibia', "iso_code" => 'NA'),
            array("name" => 'Nauru', "iso_code" => 'NR'),
            array("name" => 'Nepal', "iso_code" => 'NP'),
            array("name" => 'Netherlands', "iso_code" => 'NL'),
            array("name" => 'Netherlands Antilles', "iso_code" => 'AN'),
            array("name" => 'New Caledonia', "iso_code" => 'NC'),
            array("name" => 'New Zealand', "iso_code" => 'NZ'),
            array("name" => 'Nicaragua', "iso_code" => 'NI'),
            array("name" => 'Niger', "iso_code" => 'NE'),
            array("name" => 'Nigeria', "iso_code" => 'NG'),
            array("name" => 'Niue', "iso_code" => 'NU'),
            array("name" => 'Norfolk Island', "iso_code" => 'NF'),
            array("name" => 'Northern Mariana Islands', "iso_code" => 'MP'),
            array("name" => 'Norway', "iso_code" => 'NO'),
            array("name" => 'Oman', "iso_code" => 'OM'),
            array("name" => 'Pakistan', "iso_code" => 'PK'),
            array("name" => 'Palau', "iso_code" => 'PW'),
            array("name" => 'Palestine', "iso_code" => 'PS'),
            array("name" => 'Panama', "iso_code" => 'PA'),
            array("name" => 'Papua New Guinea', "iso_code" => 'PG'),
            array("name" => 'Paraguay', "iso_code" => 'PY'),
            array("name" => 'Peru', "iso_code" => 'PE'),
            array("name" => 'Philippines', "iso_code" => 'PH'),
            array("name" => 'Pitcairn', "iso_code" => 'PN'),
            array("name" => 'Poland', "iso_code" => 'PL'),
            array("name" => 'Portugal', "iso_code" => 'PT'),
            array("name" => 'Puerto Rico', "iso_code" => 'PR'),
            array("name" => 'Qatar', "iso_code" => 'QA'),
            array("name" => 'Reunion', "iso_code" => 'RE'),
            array("name" => 'Romania', "iso_code" => 'RO'),
            array("name" => 'Russian Federation', "iso_code" => 'RU'),
            array("name" => 'Rwanda', "iso_code" => 'RW'),
            array("name" => 'Saint Helena', "iso_code" => 'SH'),
            array("name" => 'Saint Kitts and Nevis', "iso_code" => 'KN'),
            array("name" => 'Saint Lucia', "iso_code" => 'LC'),
            array("name" => 'Saint Pierre and Miquelon', "iso_code" => 'PM'),
            array("name" => 'Saint Vincent and the Grenadines', "iso_code" => 'VC'),
            array("name" => 'Samoa', "iso_code" => 'WS'),
            array("name" => 'San Marino', "iso_code" => 'SM'),
            array("name" => 'Sao Tome and Principe', "iso_code" => 'ST'),
            array("name" => 'Saudi Arabia', "iso_code" => 'SA'),
            array("name" => 'Senegal', "iso_code" => 'SN'),
            array("name" => 'Serbia', "iso_code" => 'RS'),
            array("name" => 'Seychelles', "iso_code" => 'SC'),
            array("name" => 'Sierra Leone', "iso_code" => 'SL'),
            array("name" => 'Singapore', "iso_code" => 'SG'),
            array("name" => 'Slovakia', "iso_code" => 'SK'),
            array("name" => 'Slovenia', "iso_code" => 'SI'),
            array("name" => 'Solomon Islands', "iso_code" => 'SB'),
            array("name" => 'Somalia', "iso_code" => 'SO'),
            array("name" => 'South Africa', "iso_code" => 'ZA'),
            array("name" => 'South Georgia and the South Sandwich Islands', "iso_code" => 'GS'),
            array("name" => 'Spain', "iso_code" => 'ES'),
            array("name" => 'Sri Lanka', "iso_code" => 'LK'),
            array("name" => 'Sudan', "iso_code" => 'SD'),
            array("name" => 'Suriname', "iso_code" => 'SR'),
            array("name" => 'Svalbard and Jan Mayen', "iso_code" => 'SJ'),
            array("name" => 'Swaziland', "iso_code" => 'SZ'),
            array("name" => 'Sweden', "iso_code" => 'SE'),
            array("name" => 'Switzerland', "iso_code" => 'CH'),
            array("name" => 'Syria', "iso_code" => 'SY'),
            array("name" => 'Taiwan, Province of China', "iso_code" => 'TW'),
            array("name" => 'Tajikistan', "iso_code" => 'TJ'),
            array("name" => 'Tanzania, United Republic of', "iso_code" => 'TZ'),
            array("name" => 'Thailand', "iso_code" => 'TH'),
            array("name" => 'Timor-Leste', "iso_code" => 'TL'),
            array("name" => 'Togo', "iso_code" => 'TG'),
            array("name" => 'Tokelau', "iso_code" => 'TK'),
            array("name" => 'Tonga', "iso_code" => 'TO'),
            array("name" => 'Trinidad and Tobago', "iso_code" => 'TT'),
            array("name" => 'Tunisia', "iso_code" => 'TN'),
            array("name" => 'Turkey', "iso_code" => 'TR'),
            array("name" => 'Turkmenistan', "iso_code" => 'TM'),
            array("name" => 'Turks and Caicos Islands', "iso_code" => 'TC'),
            array("name" => 'Tuvalu', "iso_code" => 'TV'),
            array("name" => 'Uganda', "iso_code" => 'UG'),
            array("name" => 'Ukraine', "iso_code" => 'UA'),
            array("name" => 'United Arab Emirates', "iso_code" => 'AE'),
            array("name" => 'United Kingdom', "iso_code" => 'GB'),
            array("name" => 'United States', "iso_code" => 'US'),
            array("name" => 'United States Minor Outlying Islands', "iso_code" => 'UM'),
            array("name" => 'Uruguay', "iso_code" => 'UY'),
            array("name" => 'Uzbekistan', "iso_code" => 'UZ'),
            array("name" => 'Vanuatu', "iso_code" => 'VU'),
            array("name" => 'Venezuela', "iso_code" => 'VE'),
            array("name" => 'Vietnam', "iso_code" => 'VN'),
            array("name" => 'Virgin Islands, British', "iso_code" => 'VG'),
            array("name" => 'Virgin Islands, U.S.', "iso_code" => 'VI'),
            array("name" => 'Wallis and Futuna', "iso_code" => 'WF'),
            array("name" => 'Western Sahara', "iso_code" => 'EH'),
            array("name" => 'Yemen', "iso_code" => 'YE'),
            array("name" => 'Zambia', "iso_code" => 'ZM'),
            array("name" => 'Zimbabwe', "iso_code" => 'ZW'),
            array("name" => 'Montenegro', "iso_code" => 'ME')
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
