<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('iso_code_2');
            $table->string('iso_code_3');
            $table->boolean('is_active')->default(true);
        });

        \DB::table('countries')->insert([
            array("name" => 'Afghanistan', "iso_code_2" => 'AF', 'iso_code_3' => 'AFG', 'is_active' => true),
            array("name" => 'Åland Islands', "iso_code_2" => 'AX', 'iso_code_3' => 'ALA', 'is_active' => true),
            array("name" => 'Albania', "iso_code_2" => 'AL', 'iso_code_3' => 'ALB', 'is_active' => true),
            array("name" => 'Algeria', "iso_code_2" => 'DZ', 'iso_code_3' => 'DZA', 'is_active' => true),
            array("name" => 'American Samoa', "iso_code_2" => 'AS', 'iso_code_3' => 'ASM', 'is_active' => true),
            array("name" => 'Andorra', "iso_code_2" => 'AD', 'iso_code_3' => 'AND', 'is_active' => true),
            array("name" => 'Angola', "iso_code_2" => 'AO', 'iso_code_3' => 'AGO', 'is_active' => true),
            array("name" => 'Anguilla', "iso_code_2" => 'AI', 'iso_code_3' => 'AIA', 'is_active' => true),
            array("name" => 'Antarctica', "iso_code_2" => 'AQ', 'iso_code_3' => 'ATA', 'is_active' => true),
            array("name" => 'Antigua and Barbuda', "iso_code_2" => 'AG', 'iso_code_3' => 'ATG', 'is_active' => true),
            array("name" => 'Argentina', "iso_code_2" => 'AR', 'iso_code_3' => 'ARG', 'is_active' => true),
            array("name" => 'Armenia', "iso_code_2" => 'AM', 'iso_code_3' => 'ARM', 'is_active' => true),
            array("name" => 'Aruba', "iso_code_2" => 'AW', 'iso_code_3' => 'ABW', 'is_active' => true),
            array("name" => 'Australia', "iso_code_2" => 'AU', 'iso_code_3' => 'AUS', 'is_active' => true),
            array("name" => 'Austria', "iso_code_2" => 'AT', 'iso_code_3' => 'AUT', 'is_active' => true),
            array("name" => 'Azerbaijan', "iso_code_2" => 'AZ', 'iso_code_3' => 'AZE', 'is_active' => true),
            array("name" => 'Bahamas', "iso_code_2" => 'BS', 'iso_code_3' => 'BHS', 'is_active' => true),
            array("name" => 'Bahrain', "iso_code_2" => 'BH', 'iso_code_3' => 'BHR', 'is_active' => true),
            array("name" => 'Bangladesh', "iso_code_2" => 'BD', 'iso_code_3' => 'BGD', 'is_active' => true),
            array("name" => 'Barbados', "iso_code_2" => 'BB', 'iso_code_3' => 'BRB', 'is_active' => true),
            array("name" => 'Belarus', "iso_code_2" => 'BY', 'iso_code_3' => 'BLR', 'is_active' => true),
            array("name" => 'Belgium', "iso_code_2" => 'BE', 'iso_code_3' => 'BEL', 'is_active' => true),
            array("name" => 'Belize', "iso_code_2" => 'BZ', 'iso_code_3' => 'BLZ', 'is_active' => true),
            array("name" => 'Benin', "iso_code_2" => 'BJ', 'iso_code_3' => 'BEN', 'is_active' => true),
            array("name" => 'Bermuda', "iso_code_2" => 'BM', 'iso_code_3' => 'BMU', 'is_active' => true),
            array("name" => 'Bhutan', "iso_code_2" => 'BT', 'iso_code_3' => 'BTN', 'is_active' => true),
            array("name" => 'Bolivia', "iso_code_2" => 'BO', 'iso_code_3' => 'BOL', 'is_active' => true),
            array("name" => 'Bosnia and Herzegovina', "iso_code_2" => 'BA', 'iso_code_3' => 'BIH', 'is_active' => true),
            array("name" => 'Botswana', "iso_code_2" => 'BW', 'iso_code_3' => 'BWA', 'is_active' => true),
            array("name" => 'Bouvet Island', "iso_code_2" => 'BV', 'iso_code_3' => 'BVT', 'is_active' => true),
            array("name" => 'Brazil', "iso_code_2" => 'BR', 'iso_code_3' => 'BRA', 'is_active' => true),
            array("name" => 'British Indian Ocean Territory', "iso_code_2" => 'IO', 'iso_code_3' => 'IOT', 'is_active' => true),
            array("name" => 'Brunei Darussalam', "iso_code_2" => 'BN', 'iso_code_3' => 'BRN', 'is_active' => true),
            array("name" => 'Bulgaria', "iso_code_2" => 'BG', 'iso_code_3' => 'BGR', 'is_active' => true),
            array("name" => 'Burkina Faso', "iso_code_2" => 'BF', 'iso_code_3' => 'BFA', 'is_active' => true),
            array("name" => 'Burundi', "iso_code_2" => 'BI', 'iso_code_3' => 'BDI', 'is_active' => true),
            array("name" => 'Cambodia', "iso_code_2" => 'KH', 'iso_code_3' => 'KHM', 'is_active' => true),
            array("name" => 'Cameroon', "iso_code_2" => 'CM', 'iso_code_3' => 'CMR', 'is_active' => true),
            array("name" => 'Canada', "iso_code_2" => 'CA', 'iso_code_3' => 'CAN', 'is_active' => true),
            array("name" => 'Cape Verde', "iso_code_2" => 'CV', 'iso_code_3' => 'CPV', 'is_active' => true),
            array("name" => 'Cayman Islands', "iso_code_2" => 'KY', 'iso_code_3' => 'CYM', 'is_active' => true),
            array("name" => 'Central African Republic', "iso_code_2" => 'CF', 'iso_code_3' => 'CAF', 'is_active' => true),
            array("name" => 'Chad', "iso_code_2" => 'TD', 'iso_code_3' => 'TCD', 'is_active' => true),
            array("name" => 'Chile', "iso_code_2" => 'CL', 'iso_code_3' => 'CHL', 'is_active' => true),
            array("name" => 'China', "iso_code_2" => 'CN', 'iso_code_3' => 'CHN', 'is_active' => true),
            array("name" => 'Christmas Island', "iso_code_2" => 'CX', 'iso_code_3' => 'CXR', 'is_active' => true),
            array("name" => 'Cocos (Keeling) Islands', "iso_code_2" => 'CC', 'iso_code_3' => 'CCK', 'is_active' => true),
            array("name" => 'Colombia', "iso_code_2" => 'CO', 'iso_code_3' => 'COL', 'is_active' => true),
            array("name" => 'Comoros', "iso_code_2" => 'KM', 'iso_code_3' => 'COM', 'is_active' => true),
            array("name" => 'Congo', "iso_code_2" => 'CG', 'iso_code_3' => 'COG', 'is_active' => true),
            array("name" => 'Congo, The Democratic Republic of the', "iso_code_2" => 'CD', 'iso_code_3' => 'COD', 'is_active' => true),
            array("name" => 'Cook Islands', "iso_code_2" => 'CK', 'iso_code_3' => 'CKI', 'is_active' => true),
            array("name" => 'Costa Rica', "iso_code_2" => 'CR', 'iso_code_3' => 'CRI', 'is_active' => true),
            array("name" => 'Cote D\'Ivoire', "iso_code_2" => 'CI', 'iso_code_3' => 'CIV', 'is_active' => true),
            array("name" => 'Croatia', "iso_code_2" => 'HR', 'iso_code_3' => 'HRV', 'is_active' => true),
            array("name" => 'Cuba', "iso_code_2" => 'CU', 'iso_code_3' => 'CUB', 'is_active' => true),
            array("name" => 'Cyprus', "iso_code_2" => 'CY', 'iso_code_3' => 'CYP', 'is_active' => true),
            array("name" => 'Czech Republic', "iso_code_2" => 'CZ', 'iso_code_3' => 'CZE', 'is_active' => true),
            array("name" => 'Denmark', "iso_code_2" => 'DK', 'iso_code_3' => 'DNK', 'is_active' => true),
            array("name" => 'Djibouti', "iso_code_2" => 'DJ', 'iso_code_3' => 'DJI', 'is_active' => true),
            array("name" => 'Dominica', "iso_code_2" => 'DM', 'iso_code_3' => 'DMA', 'is_active' => true),
            array("name" => 'Dominican Republic', "iso_code_2" => 'DO', 'iso_code_3' => 'DOM', 'is_active' => true),
            array("name" => 'Ecuador', "iso_code_2" => 'EC', 'iso_code_3' => 'ECU', 'is_active' => true),
            array("name" => 'Egypt', "iso_code_2" => 'EG', 'iso_code_3' => 'EGY', 'is_active' => true),
            array("name" => 'El Salvador', "iso_code_2" => 'SV', 'iso_code_3' => 'SLV', 'is_active' => true),
            array("name" => 'Equatorial Guinea', "iso_code_2" => 'GQ', 'iso_code_3' => 'GNQ', 'is_active' => true),
            array("name" => 'Eritrea', "iso_code_2" => 'ER', 'iso_code_3' => 'ERI', 'is_active' => true),
            array("name" => 'Estonia', "iso_code_2" => 'EE', 'iso_code_3' => 'EST', 'is_active' => true),
            array("name" => 'Ethiopia', "iso_code_2" => 'ET', 'iso_code_3' => 'ETH', 'is_active' => true),
            array("name" => 'Falkland Islands (Malvinas)', "iso_code_2" => 'FK', 'iso_code_3' => 'FLK', 'is_active' => true),
            array("name" => 'Faroe Islands', "iso_code_2" => 'FO', 'iso_code_3' => 'FRO', 'is_active' => true),
            array("name" => 'Fiji', "iso_code_2" => 'FJ', 'iso_code_3' => 'FJI', 'is_active' => true),
            array("name" => 'Finland', "iso_code_2" => 'FI', 'iso_code_3' => 'FIN', 'is_active' => true),
            array("name" => 'France', "iso_code_2" => 'FR', 'iso_code_3' => 'FRA', 'is_active' => true),
            array("name" => 'French Guiana', "iso_code_2" => 'GF', 'iso_code_3' => 'GUF', 'is_active' => true),
            array("name" => 'French Polynesia', "iso_code_2" => 'PF', 'iso_code_3' => 'PYF', 'is_active' => true),
            array("name" => 'French Southern Territories', "iso_code_2" => 'TF', 'iso_code_3' => 'ATF', 'is_active' => true),
            array("name" => 'Gabon', "iso_code_2" => 'GA', 'iso_code_3' => 'GAB', 'is_active' => true),
            array("name" => 'Gambia', "iso_code_2" => 'GM', 'iso_code_3' => 'GMB', 'is_active' => true),
            array("name" => 'Georgia', "iso_code_2" => 'GE', 'iso_code_3' => 'GEO', 'is_active' => true),
            array("name" => 'Germany', "iso_code_2" => 'DE', 'iso_code_3' => 'DEU', 'is_active' => true),
            array("name" => 'Ghana', "iso_code_2" => 'GH', 'iso_code_3' => 'GHA', 'is_active' => true),
            array("name" => 'Gibraltar', "iso_code_2" => 'GI', 'iso_code_3' => 'GIB', 'is_active' => true),
            array("name" => 'Greece', "iso_code_2" => 'GR', 'iso_code_3' => 'GRC', 'is_active' => true),
            array("name" => 'Greenland', "iso_code_2" => 'GL', 'iso_code_3' => 'GRL', 'is_active' => true),
            array("name" => 'Grenada', "iso_code_2" => 'GD', 'iso_code_3' => 'GRD', 'is_active' => true),
            array("name" => 'Guadeloupe', "iso_code_2" => 'GP', 'iso_code_3' => 'GLP', 'is_active' => true),
            array("name" => 'Guam', "iso_code_2" => 'GU', 'iso_code_3' => 'GUM', 'is_active' => true),
            array("name" => 'Guatemala', "iso_code_2" => 'GT', 'iso_code_3' => 'GTM', 'is_active' => true),
            array("name" => 'Guernsey', "iso_code_2" => 'GG', 'iso_code_3' => 'GGY', 'is_active' => true),
            array("name" => 'Guinea', "iso_code_2" => 'GN', 'iso_code_3' => 'GIN', 'is_active' => true),
            array("name" => 'Guinea-Bissau', "iso_code_2" => 'GW', 'iso_code_3' => 'GNB', 'is_active' => true),
            array("name" => 'Guyana', "iso_code_2" => 'GY', 'iso_code_3' => 'GUY', 'is_active' => true),
            array("name" => 'Haiti', "iso_code_2" => 'HT', 'iso_code_3' => 'HTI', 'is_active' => true),
            array("name" => 'Heard Island and Mcdonald Islands', "iso_code_2" => 'HM', 'iso_code_3' => 'HMD', 'is_active' => true),
            array("name" => 'Holy See (Vatican City State)', "iso_code_2" => 'VA', 'iso_code_3' => 'VAT', 'is_active' => true),
            array("name" => 'Honduras', "iso_code_2" => 'HN', 'iso_code_3' => 'HND', 'is_active' => true),
            array("name" => 'Hong Kong', "iso_code_2" => 'HK', 'iso_code_3' => 'HKG', 'is_active' => true),
            array("name" => 'Hungary', "iso_code_2" => 'HU', 'iso_code_3' => 'HUN', 'is_active' => true),
            array("name" => 'Iceland', "iso_code_2" => 'IS', 'iso_code_3' => 'ISL', 'is_active' => true),
            array("name" => 'India', "iso_code_2" => 'IN', 'iso_code_3' => 'IND', 'is_active' => true),
            array("name" => 'Indonesia', "iso_code_2" => 'ID', 'iso_code_3' => 'IDN', 'is_active' => true),
            array("name" => 'Iran, Islamic Republic Of', "iso_code_2" => 'IR', 'iso_code_3' => 'IRN', 'is_active' => true),
            array("name" => 'Iraq', "iso_code_2" => 'IQ', 'iso_code_3' => 'IRQ', 'is_active' => true),
            array("name" => 'Ireland', "iso_code_2" => 'IE', 'iso_code_3' => 'IRL', 'is_active' => true),
            array("name" => 'Isle of Man', "iso_code_2" => 'IM', 'iso_code_3' => 'IMN', 'is_active' => true),
            array("name" => 'Israel', "iso_code_2" => 'IL', 'iso_code_3' => 'ISR', 'is_active' => true),
            array("name" => 'Italy', "iso_code_2" => 'IT', 'iso_code_3' => 'ITA', 'is_active' => true),
            array("name" => 'Jamaica', "iso_code_2" => 'JM', 'iso_code_3' => 'JAM', 'is_active' => true),
            array("name" => 'Japan', "iso_code_2" => 'JP', 'iso_code_3' => 'JPN', 'is_active' => true),
            array("name" => 'Jersey', "iso_code_2" => 'JE', 'iso_code_3' => 'JEY', 'is_active' => true),
            array("name" => 'Jordan', "iso_code_2" => 'JO', 'iso_code_3' => 'JOR', 'is_active' => true),
            array("name" => 'Kazakhstan', "iso_code_2" => 'KZ', 'iso_code_3' => 'KAZ', 'is_active' => true),
            array("name" => 'Kenya', "iso_code_2" => 'KE', 'iso_code_3' => 'KEN', 'is_active' => true),
            array("name" => 'Kiribati', "iso_code_2" => 'KI', 'iso_code_3' => 'KIR', 'is_active' => true),
            array("name" => 'Korea, Democratic People\'S Republic of', "iso_code_2" => 'KP', 'iso_code_3' => 'KOR', 'is_active' => true),
            array("name" => 'Korea, Republic of', "iso_code_2" => 'KR', 'iso_code_3' => 'KOR', 'is_active' => true),
            array("name" => 'Kuwait', "iso_code_2" => 'KW', 'iso_code_3' => 'KWT', 'is_active' => true),
            array("name" => 'Kyrgyzstan', "iso_code_2" => 'KG', 'iso_code_3' => 'KGZ', 'is_active' => true),
            array("name" => 'Laos', "iso_code_2" => 'LA', 'iso_code_3' => 'LAO', 'is_active' => true),
            array("name" => 'Latvia', "iso_code_2" => 'LV', 'iso_code_3' => 'LVA', 'is_active' => true),
            array("name" => 'Lebanon', "iso_code_2" => 'LB', 'iso_code_3' => 'LBN', 'is_active' => true),
            array("name" => 'Lesotho', "iso_code_2" => 'LS', 'iso_code_3' => 'LSO', 'is_active' => true),
            array("name" => 'Liberia', "iso_code_2" => 'LR', 'iso_code_3' => 'LBR', 'is_active' => true),
            array("name" => 'Libya', "iso_code_2" => 'LY', 'iso_code_3' => 'LBY', 'is_active' => true),
            array("name" => 'Liechtenstein', "iso_code_2" => 'LI', 'iso_code_3' => 'LIE', 'is_active' => true),
            array("name" => 'Lithuania', "iso_code_2" => 'LT', 'iso_code_3' => 'LTU', 'is_active' => true),
            array("name" => 'Luxembourg', "iso_code_2" => 'LU', 'iso_code_3' => 'LUX', 'is_active' => true),
            array("name" => 'Macao', "iso_code_2" => 'MO', 'iso_code_3' => 'MAC', 'is_active' => true),
            array("name" => 'North Macedonia', "iso_code_2" => 'MK', 'iso_code_3' => 'MKD', 'is_active' => true),
            array("name" => 'Madagascar', "iso_code_2" => 'MG', 'iso_code_3' => 'MDG', 'is_active' => true),
            array("name" => 'Malawi', "iso_code_2" => 'MW', 'iso_code_3' => 'MWI', 'is_active' => true),
            array("name" => 'Malaysia', "iso_code_2" => 'MY', 'iso_code_3' => 'MYS', 'is_active' => true),
            array("name" => 'Maldives', "iso_code_2" => 'MV', 'iso_code_3' => 'MDV', 'is_active' => true),
            array("name" => 'Mali', "iso_code_2" => 'ML', 'iso_code_3' => 'MLI', 'is_active' => true),
            array("name" => 'Malta', "iso_code_2" => 'MT', 'iso_code_3' => 'MLT', 'is_active' => true),
            array("name" => 'Marshall Islands', "iso_code_2" => 'MH', 'iso_code_3' => 'MHL', 'is_active' => true),
            array("name" => 'Martinique', "iso_code_2" => 'MQ', 'iso_code_3' => 'MTQ', 'is_active' => true),
            array("name" => 'Mauritania', "iso_code_2" => 'MR', 'iso_code_3' => 'MRT', 'is_active' => true),
            array("name" => 'Mauritius', "iso_code_2" => 'MU', 'iso_code_3' => 'MUS', 'is_active' => true),
            array("name" => 'Mayotte', "iso_code_2" => 'YT', 'iso_code_3' => 'MYT', 'is_active' => true),
            array("name" => 'Mexico', "iso_code_2" => 'MX', 'iso_code_3' => 'MEX', 'is_active' => true),
            array("name" => 'Micronesia, Federated States of', "iso_code_2" => 'FM', 'iso_code_3' => 'FSM', 'is_active' => true),
            array("name" => 'Moldova, Republic of', "iso_code_2" => 'MD', 'iso_code_3' => 'MDA', 'is_active' => true),
            array("name" => 'Monaco', "iso_code_2" => 'MC', 'iso_code_3' => 'MCO', 'is_active' => true),
            array("name" => 'Mongolia', "iso_code_2" => 'MN', 'iso_code_3' => 'MNG', 'is_active' => true),
            array("name" => 'Montserrat', "iso_code_2" => 'MS', 'iso_code_3' => 'MSR', 'is_active' => true),
            array("name" => 'Morocco', "iso_code_2" => 'MA', 'iso_code_3' => 'MAR', 'is_active' => true),
            array("name" => 'Mozambique', "iso_code_2" => 'MZ', 'iso_code_3' => 'MOZ', 'is_active' => true),
            array("name" => 'Myanmar', "iso_code_2" => 'MM', 'iso_code_3' => 'MMR', 'is_active' => true),
            array("name" => 'Namibia', "iso_code_2" => 'NA', 'iso_code_3' => 'NAM', 'is_active' => true),
            array("name" => 'Nauru', "iso_code_2" => 'NR', 'iso_code_3' => 'NRU', 'is_active' => true),
            array("name" => 'Nepal', "iso_code_2" => 'NP', 'iso_code_3' => 'NPL', 'is_active' => true),
            array("name" => 'Netherlands', "iso_code_2" => 'NL', 'iso_code_3' => 'NLD', 'is_active' => true),
            array("name" => 'Netherlands Antilles', "iso_code_2" => 'AN', 'iso_code_3' => 'ANT', 'is_active' => true),
            array("name" => 'New Caledonia', "iso_code_2" => 'NC', 'iso_code_3' => 'NCL', 'is_active' => true),
            array("name" => 'New Zealand', "iso_code_2" => 'NZ', 'iso_code_3' => 'NZL', 'is_active' => true),
            array("name" => 'Nicaragua', "iso_code_2" => 'NI', 'iso_code_3' => 'NIC', 'is_active' => true),
            array("name" => 'Niger', "iso_code_2" => 'NE', 'iso_code_3' => 'NER', 'is_active' => true),
            array("name" => 'Nigeria', "iso_code_2" => 'NG', 'iso_code_3' => 'NGA', 'is_active' => true),
            array("name" => 'Niue', "iso_code_2" => 'NU', 'iso_code_3' => 'NIU', 'is_active' => true),
            array("name" => 'Norfolk Island', "iso_code_2" => 'NF', 'iso_code_3' => 'NFK', 'is_active' => true),
            array("name" => 'Northern Mariana Islands', "iso_code_2" => 'MP', 'iso_code_3' => 'MNP', 'is_active' => true),
            array("name" => 'Norway', "iso_code_2" => 'NO', 'iso_code_3' => 'NOR', 'is_active' => true),
            array("name" => 'Oman', "iso_code_2" => 'OM', 'iso_code_3' => 'OMN', 'is_active' => true),
            array("name" => 'Pakistan', "iso_code_2" => 'PK', 'iso_code_3' => 'PAK', 'is_active' => true),
            array("name" => 'Palau', "iso_code_2" => 'PW', 'iso_code_3' => 'PLW', 'is_active' => true),
            array("name" => 'Palestine', "iso_code_2" => 'PS', 'iso_code_3' => 'PSE', 'is_active' => true),
            array("name" => 'Panama', "iso_code_2" => 'PA', 'iso_code_3' => 'PAN', 'is_active' => true),
            array("name" => 'Papua New Guinea', "iso_code_2" => 'PG', 'iso_code_3' => 'PNG', 'is_active' => true),
            array("name" => 'Paraguay', "iso_code_2" => 'PY', 'iso_code_3' => 'PRY', 'is_active' => true),
            array("name" => 'Peru', "iso_code_2" => 'PE', 'iso_code_3' => 'PER', 'is_active' => true),
            array("name" => 'Philippines', "iso_code_2" => 'PH', 'iso_code_3' => 'PHL', 'is_active' => true),
            array("name" => 'Pitcairn', "iso_code_2" => 'PN', 'iso_code_3' => 'PCN', 'is_active' => true),
            array("name" => 'Poland', "iso_code_2" => 'PL', 'iso_code_3' => 'POL', 'is_active' => true),
            array("name" => 'Portugal', "iso_code_2" => 'PT', 'iso_code_3' => 'PRT', 'is_active' => true),
            array("name" => 'Puerto Rico', "iso_code_2" => 'PR', 'iso_code_3' => 'PRI', 'is_active' => true),
            array("name" => 'Qatar', "iso_code_2" => 'QA', 'iso_code_3' => 'QAT', 'is_active' => true),
            array("name" => 'Reunion', "iso_code_2" => 'RE', 'iso_code_3' => 'REU', 'is_active' => true),
            array("name" => 'Romania', "iso_code_2" => 'RO', 'iso_code_3' => 'ROU', 'is_active' => true),
            array("name" => 'Russian Federation', "iso_code_2" => 'RU', 'iso_code_3' => 'RUS', 'is_active' => true),
            array("name" => 'Rwanda', "iso_code_2" => 'RW', 'iso_code_3' => 'RWA', 'is_active' => true),
            array("name" => 'Saint Helena', "iso_code_2" => 'SH', 'iso_code_3' => 'SHN', 'is_active' => true),
            array("name" => 'Saint Kitts and Nevis', "iso_code_2" => 'KN', 'iso_code_3' => 'KNA', 'is_active' => true),
            array("name" => 'Saint Lucia', "iso_code_2" => 'LC', 'iso_code_3' => 'LCA', 'is_active' => true),
            array("name" => 'Saint Pierre and Miquelon', "iso_code_2" => 'PM', 'iso_code_3' => 'SPM', 'is_active' => true),
            array("name" => 'Saint Vincent and the Grenadines', "iso_code_2" => 'VC', 'iso_code_3' => 'VCT', 'is_active' => true),
            array("name" => 'Samoa', "iso_code_2" => 'WS', 'iso_code_3' => 'WSM', 'is_active' => true),
            array("name" => 'San Marino', "iso_code_2" => 'SM', 'iso_code_3' => 'SMR', 'is_active' => true),
            array("name" => 'Sao Tome and Principe', "iso_code_2" => 'ST', 'iso_code_3' => 'STP', 'is_active' => true),
            array("name" => 'Saudi Arabia', "iso_code_2" => 'SA', 'iso_code_3' => 'SAU', 'is_active' => true),
            array("name" => 'Senegal', "iso_code_2" => 'SN', 'iso_code_3' => 'SEN', 'is_active' => true),
            array("name" => 'Serbia', "iso_code_2" => 'RS', 'iso_code_3' => 'SRB', 'is_active' => true),
            array("name" => 'Seychelles', "iso_code_2" => 'SC', 'iso_code_3' => 'SYC', 'is_active' => true),
            array("name" => 'Sierra Leone', "iso_code_2" => 'SL', 'iso_code_3' => 'SLE', 'is_active' => true),
            array("name" => 'Singapore', "iso_code_2" => 'SG', 'iso_code_3' => 'SGP', 'is_active' => true),
            array("name" => 'Slovakia', "iso_code_2" => 'SK', 'iso_code_3' => 'SVK', 'is_active' => true),
            array("name" => 'Slovenia', "iso_code_2" => 'SI', 'iso_code_3' => 'SVN', 'is_active' => true),
            array("name" => 'Solomon Islands', "iso_code_2" => 'SB', 'iso_code_3' => 'SLB', 'is_active' => true),
            array("name" => 'Somalia', "iso_code_2" => 'SO', 'iso_code_3' => 'SOM', 'is_active' => true),
            array("name" => 'South Africa', "iso_code_2" => 'ZA', 'iso_code_3' => 'ZAF', 'is_active' => true),
            array("name" => 'South Georgia and the South Sandwich Islands', "iso_code_2" => 'GS', 'iso_code_3' => 'SGS', 'is_active' => true),
            array("name" => 'Spain', "iso_code_2" => 'ES', 'iso_code_3' => 'ESP', 'is_active' => true),
            array("name" => 'Sri Lanka', "iso_code_2" => 'LK', 'iso_code_3' => 'LKA', 'is_active' => true),
            array("name" => 'Sudan', "iso_code_2" => 'SD', 'iso_code_3' => 'SDN', 'is_active' => true),
            array("name" => 'Suriname', "iso_code_2" => 'SR', 'iso_code_3' => 'SUR', 'is_active' => true),
            array("name" => 'Svalbard and Jan Mayen', "iso_code_2" => 'SJ', 'iso_code_3' => 'SJM', 'is_active' => true),
            array("name" => 'Swaziland', "iso_code_2" => 'SZ', 'iso_code_3' => 'SWZ', 'is_active' => true),
            array("name" => 'Sweden', "iso_code_2" => 'SE', 'iso_code_3' => 'SWE', 'is_active' => true),
            array("name" => 'Switzerland', "iso_code_2" => 'CH', 'iso_code_3' => 'CHE', 'is_active' => true),
            array("name" => 'Syria', "iso_code_2" => 'SY', 'iso_code_3' => 'SYR', 'is_active' => true),
            array("name" => 'Taiwan, Province of China', "iso_code_2" => 'TW', 'iso_code_3' => 'TWN', 'is_active' => true),
            array("name" => 'Tajikistan', "iso_code_2" => 'TJ', 'iso_code_3' => 'TJK', 'is_active' => true),
            array("name" => 'Tanzania, United Republic of', "iso_code_2" => 'TZ', 'iso_code_3' => 'TZA', 'is_active' => true),
            array("name" => 'Thailand', "iso_code_2" => 'TH', 'iso_code_3' => 'THA', 'is_active' => true),
            array("name" => 'Timor-Leste', "iso_code_2" => 'TL', 'iso_code_3' => 'TLS', 'is_active' => true),
            array("name" => 'Togo', "iso_code_2" => 'TG', 'iso_code_3' => 'TGO', 'is_active' => true),
            array("name" => 'Tokelau', "iso_code_2" => 'TK', 'iso_code_3' => 'TKL', 'is_active' => true),
            array("name" => 'Tonga', "iso_code_2" => 'TO', 'iso_code_3' => 'TON', 'is_active' => true),
            array("name" => 'Trinidad and Tobago', "iso_code_2" => 'TT', 'iso_code_3' => 'TTO', 'is_active' => true),
            array("name" => 'Tunisia', "iso_code_2" => 'TN', 'iso_code_3' => 'TUN', 'is_active' => true),
            array("name" => 'Turkey', "iso_code_2" => 'TR', 'iso_code_3' => 'TUR', 'is_active' => true),
            array("name" => 'Turkmenistan', "iso_code_2" => 'TM', 'iso_code_3' => 'TKM', 'is_active' => true),
            array("name" => 'Turks and Caicos Islands', "iso_code_2" => 'TC', 'iso_code_3' => 'TCA', 'is_active' => true),
            array("name" => 'Tuvalu', "iso_code_2" => 'TV', 'iso_code_3' => 'TUV', 'is_active' => true),
            array("name" => 'Uganda', "iso_code_2" => 'UG', 'iso_code_3' => 'UGA', 'is_active' => true),
            array("name" => 'Ukraine', "iso_code_2" => 'UA', 'iso_code_3' => 'UKR', 'is_active' => true),
            array("name" => 'United Arab Emirates', "iso_code_2" => 'AE', 'iso_code_3' => 'ARE', 'is_active' => true),
            array("name" => 'United Kingdom', "iso_code_2" => 'GB', 'iso_code_3' => 'GBR', 'is_active' => true),
            array("name" => 'United States', "iso_code_2" => 'US', 'iso_code_3' => 'USA', 'is_active' => true),
            array("name" => 'United States Minor Outlying Islands', "iso_code_2" => 'UM', 'iso_code_3' => 'UMI', 'is_active' => true),
            array("name" => 'Uruguay', "iso_code_2" => 'UY', 'iso_code_3' => 'URY', 'is_active' => true),
            array("name" => 'Uzbekistan', "iso_code_2" => 'UZ', 'iso_code_3' => 'UZB', 'is_active' => true),
            array("name" => 'Vanuatu', "iso_code_2" => 'VU', 'iso_code_3' => 'VUT', 'is_active' => true),
            array("name" => 'Venezuela', "iso_code_2" => 'VE', 'iso_code_3' => 'VEN', 'is_active' => true),
            array("name" => 'Vietnam', "iso_code_2" => 'VN', 'iso_code_3' => 'VNM', 'is_active' => true),
            array("name" => 'Virgin Islands, British', "iso_code_2" => 'VG', 'iso_code_3' => 'VGB', 'is_active' => true),
            array("name" => 'Virgin Islands, U.S.', "iso_code_2" => 'VI', 'iso_code_3' => 'VIR', 'is_active' => true),
            array("name" => 'Wallis and Futuna', "iso_code_2" => 'WF', 'iso_code_3' => 'WLF', 'is_active' => true),
            array("name" => 'Western Sahara', "iso_code_2" => 'EH', 'iso_code_3' => 'ESH', 'is_active' => true),
            array("name" => 'Yemen', "iso_code_2" => 'YE', 'iso_code_3' => 'YEM', 'is_active' => true),
            array("name" => 'Zambia', "iso_code_2" => 'ZM', 'iso_code_3' => 'ZMB', 'is_active' => true),
            array("name" => 'Zimbabwe', "iso_code_2" => 'ZW', 'iso_code_3' => 'ZWE', 'is_active' => true),
            array("name" => 'Montenegro', "iso_code_2" => 'ME', 'iso_code_3' => 'MNE', 'is_active' => true)
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
