export const SET_SEARCH_BAR_SEARCH_RESULTS = "SET_SEARCH_BAR_SEARCH_RESULTS";
export const SET_ACCOMMODATIONS_SEARCH_RESULTS = "SET_ACCOMMODATIONS_SEARCH_RESULTS";
export const SET_FILTERS = "SET_FILTERS";
export const SET_TOTAL_ACCOMMODATIONS_FOUND = "SET_TOTAL_ACCOMMODATIONS_FOUND";
