<?php

return [
    'days_of_week' => [
        [ 'id' => "monday", 'name' => "Monday" ],
        [ 'id' => "tuesday", 'name' => "Tuesday" ],
        [ 'id' => "wednesday", 'name' => "Wednesday" ],
        [ 'id' => "thursday", 'name' => "Thursday" ],
        [ 'id' => "friday", 'name' => "Friday" ],
        [ 'id' => "saturday", 'name' => "Saturday" ],
        [ 'id' => "sunday", 'name' => "Sunday" ],
    ],
    'country_currency_map' => [
        'RS' => 'RSD',
        'BA' => 'EUR',
        'HR' => 'EUR',
        'ME' => 'EUR',
        'SI' => 'EUR',
        'MK' => 'EUR',
        'US' => 'USD',
        'GB' => 'GBP',
        'CH' => 'CHF',
        'CA' => 'CAD',
        'AU' => 'AUD',
        'JP' => 'JPY',
        'CN' => 'CNY',
        'IT' => 'EUR',
        'FR' => 'EUR',
        'DE' => 'EUR',
        'ES' => 'EUR',
        'NL' => 'EUR',
        'BE' => 'EUR',
        'AT' => 'EUR',
        'PT' => 'EUR',
        'IE' => 'EUR',
        'GR' => 'EUR',
        'LU' => 'EUR',
        'FI' => 'EUR',
        'SE' => 'SEK',
        'NO' => 'NOK',
        'DK' => 'DKK',
        'HU' => 'HUF',
        'PL' => 'PLN',
        'CZ' => 'CZK',
        'SK' => 'EUR',
        'RO' => 'RON',
        'BG' => 'BGN',
        'TR' => 'TRY',
    ]
];
