<?php

return [

    'ui_constants' => [
        'sort_options' => [
            ['id' => "price_asc", 'name' => 'ui.price_asc'],
            ['id' => "price_desc", 'name' => 'ui.price_desc'],
            ['id' => "newest", 'name' => 'ui.newest'],
            // ['id' => "rating", 'name' => 'ui.rating'],
            // ['id' => "reviews", 'name' => 'ui.reviews'],
        ],
        'days_of_week' => [
            ['id' => "monday", 'name' => 'ui.monday'],
            ['id' => "tuesday", 'name' => 'ui.tuesday'],
            ['id' => "wednesday", 'name' => 'ui.wednesday'],
            ['id' => "thursday", 'name' => 'ui.thursday'],
            ['id' => "friday", 'name' => 'ui.friday'],
            ['id' => "saturday", 'name' => 'ui.saturday'],
            ['id' => "sunday", 'name' => 'ui.sunday'],
        ],
    ],
    'country_currency_map' => [
        'RS' => 'RSD',
        'BA' => 'EUR',
        'HR' => 'EUR',
        'ME' => 'EUR',
        'SI' => 'EUR',
        'MK' => 'EUR',
        'US' => 'USD',
        'GB' => 'GBP',
        'CH' => 'CHF',
        'CA' => 'CAD',
        'AU' => 'AUD',
        'JP' => 'JPY',
        'CN' => 'CNY',
        'IT' => 'EUR',
        'FR' => 'EUR',
        'DE' => 'EUR',
        'ES' => 'EUR',
        'NL' => 'EUR',
        'BE' => 'EUR',
        'AT' => 'EUR',
        'PT' => 'EUR',
        'IE' => 'EUR',
        'GR' => 'EUR',
        'LU' => 'EUR',
        'FI' => 'EUR',
        'SE' => 'SEK',
        'NO' => 'NOK',
        'DK' => 'DKK',
        'HU' => 'HUF',
        'PL' => 'PLN',
        'CZ' => 'CZK',
        'SK' => 'EUR',
        'RO' => 'RON',
        'BG' => 'BGN',
        'TR' => 'TRY',
    ]
];
