export const SET_CALENDAR_LOADING = "SET_CALENDAR_LOADING";
export const SET_CALENDAR_ERROR = "SET_CALENDAR_ERROR";
export const SET_BOOKINGS = "SET_BOOKINGS";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_CURRENT_MONTH = "SET_CURRENT_MONTH";
export const SET_CURRENT_YEAR = "SET_CURRENT_YEAR";
