export const SET_ACCOMMODATION_DRAFT_STATS = "SET_ACCOMMODATION_DRAFT_STATS";
export const SET_HOSTING_LOADING = "SET_HOSTING_LOADING";

//Fees
export const SET_FEE_TYPES = "SET_FEE_TYPES";
export const SET_FEE_CHARGE_TYPES = "SET_FEE_CHARGE_TYPES";
